### ISSUE TITLE
Get values of IPFIX IP addresses in human readable format..

### ISSUE THREAD

**Issue by vigodeltoro** [netsampler/goflow2#104]
Hi there.. 

I'm trying around with the goflow2, kafka, clickhouse pipeline and I'm searching for a way to make the IP adresses of the inserted IPFIX flows human readable. Maybe it is a question more related to Clickhouse, but I want to try my luck here as well ;).. 

As seen in flow.proto protobuf schema the datatypes of the fields with IP adresses are bytes format. But that is not really handy for me to save it in CH database, because I don't know how to read/make use of the byte objects in selects in DB usage. If I use the DB Pipeline tutorial I saw the CH DB column for that is fixed_string(16) but with that I got also byte objects in DB table. 

--- snip ----

  // Sampler information
  bytes SamplerAddress = 11;

  // Found inside packet
  uint64 TimeFlowStart = 38;
  uint64 TimeFlowEnd = 5;
  uint64 TimeFlowStartMs = 63;
  uint64 TimeFlowEndMs = 64;

  // Size of the sampled packet
  uint64 Bytes = 9;
  uint64 Packets = 10;

  // Source/destination addresses
  bytes SrcAddr = 6;
  bytes DstAddr = 7;

---- snap ---

My tries to change the format in flow.proto  ( SrcAddress, DstAddress, SamplerAdress ) to string ( because I think the docker container compile the Proto format file at startup ? ) ended up with byte objects in the specific columns of the CH DB.
That are the DB schema to read from KAFKA:

CREATE TABLE IF NOT EXISTS sisr_dev.kafka_raw_goflow2_test1_proto_ipfix_consumer ON CLUSTER "dev-ch-cluster" (
        Samplingrate UInt64,
        SequenceNum UInt32,
        SrcAddr String,
        DstAddr String,
        Bytes UInt64,
        Packets UInt64,
        SamplerAddress String,
        NextHop String,
        Proto UInt32,
        SrcPort UInt32,
        DstPort UInt32,
        SrcMac UInt64,
        DstMac UInt64,
        Etype UInt32,
        TimeFlowStart UInt64,
        IngressVrfID UInt32,
        TimeFlowStartMs UInt64,
        TimeFlowEndMs UInt64,
   )
    ENGINE = Kafka () 
    SETTINGS kafka_broker_list = 
     [kafka_broker]
      kafka_topic_list = 'goflow2_test1_raw_ipfix_proto',
      kafka_group_name = 'goflow2_raw_ch_kafka', kafka_num_consumers = 8,
      kafka_thread_per_consumer = 4,
      kafka_format = 'Protobuf',
      kafka_schema = 'flow.proto:FlowMessage',
      kafka_skip_broken_messages = 1
      
Data will be written correctly into database.. everything is working like a charm excluding the thing with the byte format ip addresses.. 

Does anybody can help me ? Or has a example for better understanding and usage of the data ?

best regards and thanks .. 
Christian

**Comment by lspgn** [comment]
Hi Christian,
Try using the following to render an IP address stored as bytes into a readable string.
```
if(EType = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(SrcAddr), 13,4))), IPv6NumToString(SrcAddr))
```

Let me know if that works!

**Comment by vigodeltoro** [comment]
Hi, thanks for the fast answer.. :).. 

That query seems to work *yeah*:
SELECT IPv4NumToString(reinterpretAsUInt32(substring(reverse(SrcAddr), 13,4))) as src_ip4, IPv6NumToString(SrcAddr) as src_ip6 FROM sisr_dev.flows_raw_dview;

I changed the if(Etype .. version a little bit, because it only gives me only IPv6.. ( below a snapshot of the output of the select )

--- snip ----

│ 0.0.0.0       │ ::                                      │
│ 0.0.0.0       │ ::                                      │
│ 0.0.0.0       │ ::                                      │
│ 0.0.0.0       │ ::                                      │
│ 0.0.0.0       │ ::                                      │
│ 0.0.0.0       │ ::                                      │
│ 0.0.0.0       │ ::                                      │
│ 42.11.244.xx │ 2a0b:f4c2:xx::xx        │
│ 0.0.0.0       │ ::                                      │
│ 0.0.0.0       │ ::                                      │
│ 32.1.77.xx   │ 2001:4de0:ac10::xx:xx:xx                  │
│ 0.0.0.0       │ ::                                      │
│ 0.0.0.0       │ ::                                      │
│ 0.0.0.0       │ ::                                      │

-------- snap ---

But I'm wondering that so much rows have no IP address.. because I'm testing with a static tcpdump to compare with other tools and with pmacct and json I get for all my IPfix packages an src_ip and dst ip 

I didn't tried it with goflow2 and json.. ( I will do ) maybe it is the same in CH destination table.. and it's not a format issue.. but it is a little bit strange. Do you maybe have an idea ? 

thanks a lot :)

Best
Christian

**Comment by vigodeltoro** [comment]
Okay I checked if this occurs in json as well and it does.. 


{"Type":"IPFIX","TimeReceived":1658741332,"SequenceNum":22854725,"SamplingRate":1,"SamplerAddress":"x.x.x.x","TimeFlowStart":1657629118,"TimeFlowEnd":1657629120,"TimeFlowStartMs":1657629118699,"TimeFlowEndMs":1657629120739,"Bytes":2492,"Packets":2,"SrcAddr":"::","DstAddr":"::","Etype":34525,"Proto":17,"SrcPort":443,"DstPort":58829,"InIf":0,"OutIf":0,"SrcMac":"xx:45:xx:69:07:c8","DstMac":"88:xx:09:xx:81:49","SrcVlan":0,"DstVlan":0,"VlanId":0,"IngressVrfID":2,"EgressVrfID":0,"IPTos":0,"ForwardingStatus":0,"IPTTL":0,"TCPFlags":0,"IcmpType":0,"IcmpCode":0,"IPv6FlowLabel":0,"FragmentId":0,"FragmentOffset":0,"BiFlowDirection":0,"SrcAS":0,"DstAS":0,"NextHop":"::","NextHopAS":0,"SrcNet":0,"DstNet":0,"EtypeName":"IPv6","ProtoName":"UDP","IcmpName":""}

I also see that all sampled packages are EtypeName":"IPv6", that is suspicious, because my traffic contains very less IPv6 traffic.. 

I think there is something strange .. because if I could see an IP address like in my post before I see IPv4 and IPv6 as well which could't be in my opinion.. If I dump the traffic to a textile I can't find that IPs it seems it captures IPv6 only ?


If anybody has an idea what's wrong that would be very helpful.. issue is seen with goflow2 binary and docker container..

best .. and thanks in advance
Christian

**Comment by lspgn** [comment]
I'm assuming this is related to #105.
Let's continue on there.
