### ISSUE TITLE
SASL/SCRAM authentication for Kafka

### ISSUE THREAD

**Issue by Packetslave** [netsampler/goflow2#120]
Amazon Managed Service for Kafka (MSK) does not support SASL/PLAIN authentication, even over TSL. However, it **does** support SASL/SCRAM.

`[2022-09-12 03:44:30,722] INFO [SocketServer brokerId=2] Failed authentication with ip-10-10-101-111.us-west-2.compute.internal/INTERNAL_IP (Unsupported SASL mechanism PLAIN) (org.apache.kafka.common.network.Selector)`

For our use case (distributed goflow2 agents sending flows to regional MSK deployments), we need goflow2 to be able to support SCRAM. Fortunately, it looks like Sarama already supports it, so this should (hopefully) be straightforward. See [example code](https://github.com/Shopify/sarama/blob/main/examples/sasl_scram_client/main.go) from the Sarama repository.

I'm happy to take a crack at adding this to goflow2, if it's something you think it valuable.

**Comment by Packetslave** [comment]
Working implementation in https://github.com/netsampler/goflow2/pull/121

**Comment by lspgn** [comment]
Merged #121
