### ISSUE TITLE
Cisco NBAR / NBAR v2 Support

### ISSUE THREAD

**Issue by yusufozturk** [netsampler/goflow2#122]
Hi! Thanks for this library :)

Is there any plan to add Cisco NBAR support to handle Application IDs in the future?

Thanks.

**Comment by lspgn** [comment]
Hello
Could you give me more information on what you mean by Application IDs.
From my quick research it seems quite far from NetFlow/sFlow and I didn't find protocol info yet. So this may be out of scope.
Do you have packet capture samples?

**Comment by yusufozturk** [comment]
I think this library already supports NBAR. When I did a quick look, I didn't see anything about NBAR, so I thought it does not support it.

If device supports NBAR, it sends the application id in the "Application ID" field, here is the Wireshark screenshot:

![image](https://user-images.githubusercontent.com/928600/192570940-9ed8c76d-5fd2-4b5c-9dee-a463ad612e45.png)

So it's 95 for Application ID. Here is the definition in this library:

https://github.com/netsampler/goflow2/blob/e4bacbc4bdf26a5011bc53b37b766a21291db261/decoders/netflow/ipfix.go#L99

 So it's actually exist in the library but when I look at pb\flow.proto, I don't see Application ID. Is that a problem? I think I can use one of the CustomBytes for that, right?

Thanks for quick help btw.

**Comment by yusufozturk** [comment]
Thanks, I will do that.
