### ISSUE TITLE
Possible bug in Netflow decoder

### ISSUE THREAD

**Issue by yusufozturk** [netsampler/goflow2#123]
Hi,

There might be a possible bug here:

https://github.com/netsampler/goflow2/blob/d6caeaacddbb91131d09762cb10fcc7a6d9d91d6/decoders/netflow/netflow.go#L191

This return is in for loop, so it's weird that it returns. Previously it was in If block.

Maybe a possible bug?

Thanks.

**Comment by lspgn** [comment]
I'll have a look.
Is it causing an issue?
From what I'm reading, the for ensures the first part is returned. I agree it could be an if, unless I wanted to return more data in a single array.
When was it an if block?
