### ISSUE TITLE
Hashing for Kafka key not working ?

### ISSUE THREAD

**Issue by vigodeltoro** [netsampler/goflow2#135]
Hi Louis, 

here I am again ;)..

At first thanks for the new release, I found the time to upgrade our branch built goflow2 to v1.1.1
Goflow2 is working great :)

But nevertheless we found sth. ..because we had partitions in Kafka which where never used, we investigated how to fix that. During that investigations we found that with that configuration:

    - -transport.kafka.hashing=true
    - -format.hash=SamplerAddress,TimeReceived
    
Our keys in Kafka looks like that:

```

./kafka-console-consumer.sh --bootstrap-server kafka.***.net:9094 --topic goflow2_raw_ipfix_proto --partition 11 --property print.key=true --property print.value=false
[10 124 0 7]-1669199851-
[10 124 0 7]-1669199851-
[10 124 0 7]-1669199851-
[10 124 0 7]-1669199851-
[10 124 0 7]-1669199851-
[10 124 0 7]-1669199851-
[10 124 0 7]-1669199851-
[10 124 0 7]-1669199851-
```

But we expected a hash.. are we doing sth. wrong ?

thanks and best regards 
Christian

**Comment by lspgn** [comment]
Hello,
My apologies for the delay.

https://github.com/netsampler/goflow2/blob/d53e5f9b5a116bcb365c7c83f3272894bb44520d/format/common/hash.go#L47-L52

This just renders as string for a key that can be used by a transport. But I agree, this could be improved.
The hash is done by the Sarama library on the key using [FNV](https://pkg.go.dev/hash/fnv#New32):

https://github.com/Shopify/sarama/blob/a37f45dcee6b1e95240c17a4c60c4a960d50eaeb/partitioner.go#L162-L167

You can remove `-transport.kafka.hashing` and it will fallback on random load-balancing. I am basing my assumption on the fact you added `TimeReceived` to the list.
Hashing is required if you have something aggregating on the stream, eg: Flink, Kafka Streams.
In which case I would advise to hash by the items you're aggregating on.

You can add this to the consumer to visualize partitions
```
--property print.partition=true
```

If you run the following: is it balanced?
```bash
$ /opt/bitnami/kafka/bin/kafka-get-offsets.sh --bootstrap-server 127.0.0.1:9092 --topic flows
flows:0:932
flows:1:416
flows:2:18
flows:3:9
flows:4:2
flows:5:0
flows:6:1
flows:7:7
flows:8:2
flows:9:9
```

To increase the number of partitions
```bash
$ /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --topic flows  --partitions 10 --alter
```

**Comment by vigodeltoro** [comment]
Hi Louis, 
no worries.. it wasn't so urgent.. 

Okay.. if I understand right, we have to do some special compilations if we want to use a real hashing for the keys (Sarama library)?

 We will test the "normal" load balancing ..
 
 Maybe I can mention another request here.. 
 Do you plan a new release in near future ? Because we figured out that the bugfix about the IPv4/IPv6 template for Nokia is not in release v1.1.1.. 
 
 Thanks and best regards
 Christian

**Comment by lspgn** [comment]
Hello!

> Okay.. if I understand right, we have to do some special compilations if we want to use a real hashing for the keys (Sarama library)?

Yes, if you want the key to be a hash as well. It could reduce the size of the key but I cannot guarantee if the hash of the key (which will be a hash) will be sufficiently balanced.

>  Do you plan a new release in near future ? Because we figured out that the bugfix about the IPv4/IPv6 template for Nokia is not in release v1.1.1..

I could cut a new release in the coming weeks. Still had a few PRs I wanted to tryout before.

**Comment by vigodeltoro** [comment]
Hi Louis,
> Yes, if you want the key to be a hash as well. It could reduce the size of the key but I cannot guarantee if the hash of the key (which will be a hash) will be sufficiently balanced.

Okay.. thanks, we fixed it by changing it to another field (SrcMac) that has better entropy than SamplerAddress in our case

> I could cut a new release in the coming weeks. Still had a few PRs I wanted to tryout before.

Okay.. also thanks for that. We will nail our deployment to a special commit meanwhile.

best Christian

**Comment by lspgn** [comment]
I just cut release v1.2.0.

Also I improved a bit how keys are done with #150. Let me know if you can test.

Closing this for now.

**Comment by luciano2683** [comment]
Hello all! 
Sorry to write on the same topic.
Im running on the same situation where the messages starts well balanced accross multiple partitions and then the start to get imbalanced.

Im using this and the pre-built binary goflow2 v2.2.2

/usr/local/bin/goflow2 -listen "netflow://X.X.X.X:9995/?count=4&workers=8&queue_size=2000000" -transport kafka -transport.kafka.brokers "127.0.0.1:9092" -transport.kafka.hashing=false -transport.kafka.topic "flows" -format bin -addr "10.176.254.40:8080" -loglevel="debug"

(i had to remove the CONSUME-ID for this message, sorry)

GROUP           TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                                                                          HOST            CLIENT-ID
clickhouse      flows           2          13058673        13066597        7924            
clickhouse      flows           4          13058673        13066597        7924            
clickhouse      flows           0          13058673        13066598        7925            
clickhouse      flows           7          8935996         13066597        4130601
clickhouse      flows           6          10854447        13066597        2212150
clickhouse      flows           3          13058673        13066597        7924
clickhouse      flows           1          13058673        13066597        7924
clickhouse      flows           5          13058673        13066597        7924

Can anyone point me in the right direction?
Also, i dont know if the loglevel is correctly configured.

Ty!
