### ISSUE TITLE
Avoid using binary.Read

### ISSUE THREAD

**Issue by vincentbernat** [netsampler/goflow2#140]
Hey!

`binary.Read()` accounts for about 25% of CPU time when decoding. It's slow because:
- it requires using the `bytes.Buffer` abstraction
- it uses reflection sometimes

I think a quick win would be to scrap the function from Go source code and make it work on a slice instead. And remove the part using the reflection (and fix the caller site in Goflow).

**Comment by lspgn** [comment]
Hello!
Thank you for this suggestion.
Did you do pprof? Would the gain in packets decoded be 25% too?
Will have a look at the PR.

Do you know of any other packet decoding libraries used this approach? Also found a [blogpost](https://lemire.me/blog/2022/03/18/writing-out-large-arrays-in-go-binary-write-is-inefficient-for-large-arrays/) that seems to mention this.

**Comment by vincentbernat** [comment]
I did pprof for Akvorado:

```
goos: linux
goarch: amd64
pkg: akvorado/inlet/flow
cpu: AMD Ryzen 5 5600X 6-Core Processor
                            │ bench-3.txt  │             bench-4.txt             │
                            │    sec/op    │   sec/op     vs base                │
Netflow/with_encoding-12       7.758µ ± 3%   7.365µ ± 2%   -5.07% (p=0.000 n=10)
Netflow/without_encoding-12    7.304µ ± 2%   6.931µ ± 3%   -5.11% (p=0.000 n=10)
Sflow/with_encoding-12        14.256µ ± 1%   9.834µ ± 2%  -31.02% (p=0.000 n=10)
Sflow/without_encoding-12     13.559µ ± 2%   9.353µ ± 2%  -31.02% (p=0.000 n=10)
```

**Comment by lspgn** [comment]
Merged https://github.com/netsampler/goflow2/pull/204 for v2 as well.
Thank you!
