### ISSUE TITLE
JSON output is not standardized

### ISSUE THREAD

**Issue by romchi** [netsampler/goflow2#142]
Hello,
try use goflow2 with export to Kafka. When use Protobuf the scheme is clear and there is a name for the fields. When use JSON the field names not fully clear and not the same as in the Protobuf. Is the are explanation of fields which present in JSON output? 

Also the are type errors int SrcNet and DstNet fields, this fields need to be as _String_, but in Sflow there returns _Int_ with value 0.

It might be worth maintaining a single output format scheme for json and protobuffer ?

**Comment by lspgn** [comment]
Hi @romchi 
The default formatting uses the Golang field names from the structure which are capitalized. 

https://github.com/netsampler/goflow2/blob/d53e5f9b5a116bcb365c7c83f3272894bb44520d/pb/flow.pb.go#L86

But the generated protobuf also contains information about the JSON formatting.
For instance `SamplingRate` becoming `sampling_rate`.

Where does the type error?
`SrcNet` and `DstNet` contain the size of the network but not the full address.
My assumption was: with the IP and the size, one can recalculate the network address and save a few bytes.
I would need to look into improving it for JSON (for logs).

**Comment by lspgn** [comment]
This will be fixed in v2: #150.
`src_net` and `dst_net` are mapped as `192.168.0.0/24` for instance.
More flexibility also regarding field names and json.
