### ISSUE TITLE
Addition of TimeReceivedMs Field

### ISSUE THREAD

**Issue by fionera** [netsampler/goflow2#144]
The netflow decoder/producer has a more exact time stored but never publishes it. Should I make a PR to add it or is that intended?

**Comment by lspgn** [comment]
Hello,
It's possible although is there a use-case for time received?
I assume this is for sFlow but the actual packet time is already lost. I'm not sure for debugging as well since it's UDP and messages are not retried.
Thanks!

**Comment by lspgn** [comment]
@fionera In v2 (see #150) I changed all the timestamps to nanoseconds, this includes TimeReceived.
Closing this. Feel free to re-open if that does not cover your use-case.

**Comment by fionera** [comment]
Thank you very much :) I just wanted this as I will probably write a sflow generator which will have nanoseconds and will also support 1:1 sampling where I wont lose the packet timestamp.
