### ISSUE TITLE
Unable to see 137 common properties ID when decode ipfix

### ISSUE THREAD

**Issue by psagrera** [netsampler/goflow2#148]
Hi, 
I'm receiving a template like that 

<img width="1169" alt="template" src="https://user-images.githubusercontent.com/11019109/227139584-15e589a4-6ad1-4913-b533-b4a598865ea1.png">

and this data

<img width="1298" alt="data" src="https://user-images.githubusercontent.com/11019109/227139678-9ba0759c-84df-4ab6-a2e6-87d2537c3e7f.png">

from a juniper device.

when I look on the json decoded I see:

{"Type":"IPFIX","TimeReceived":1679496068,"SequenceNum":9331,"SamplingRate":1,"FlowDirection":0,"SamplerAddress":"192.168.2.2","TimeFlowStart":0,"TimeFlowEnd":0,"TimeFlowStartMs":0,"TimeFlowEndMs":0,"Bytes":106,"Packets":1,"SrcAddr":"10.10.10.10","DstAddr":"9.9.9.9","Etype":2048,"Proto":1,"SrcPort":0,"DstPort":0,"InIf":576,"OutIf":0,"SrcMac":"56:04:05:00:af:7c","DstMac":"56:04:05:00:d8:b5","SrcVlan":0,"DstVlan":0,"VlanId":0,"IngressVrfId":0,"EgressVrfId":0,"IpTos":0,"ForwardingStatus":0,"IpTtl":64,"TcpFlags":0,"IcmpType":0,"IcmpCode":0,"Ipv6FlowLabel":0,"FragmentId":59069,"FragmentOffset":0,"BiFlowDirection":0,"SrcAs":0,"DstAs":0,"NextHop":"","NextHopAs":0,"SrcNet":0,"DstNet":0,"BgpNextHop":[],"BgpCommunities":[],"AsPath":[],"HasMpls":true,"MplsCount":2,"Mpls_1Ttl":64,"Mpls_1Label":299792,"Mpls_2Ttl":64,"Mpls_2Label":299824,"Mpls_3Ttl":0,"Mpls_3Label":0,"MplsLastTtl":0,"MplsLastLabel":0,"MplsLabelIp":[],"ObservationDomainId":4194369536,"ObservationPointId":0,"CustomInteger_1":0,"CustomInteger_2":0,"CustomInteger_3":0,"CustomInteger_4":0,"CustomInteger_5":0,"CustomBytes_1":[],"CustomBytes_2":[],"CustomBytes_3":[],"CustomBytes_4":[],"CustomBytes_5":[]}

but nothing about 137 IPFIX_FIELD_commonPropertiesId neither 312 and 315 

what am I doing wrong ? 

find attached the .pcap 

[test4.pcap.zip](https://github.com/netsampler/goflow2/files/11048333/test4.pcap.zip)

Thanks in advance

**Comment by lspgn** [comment]
Hello Pablo,
Thank you for the extensive debug :).
Did you provide a custom configuration to GoFlow2 to allow mapping of this enterprise field?
https://github.com/netsampler/goflow2/blob/main/cmd/goflow2/mapping.yaml#L8

Otherwise, by default, not everything is decoded

**Comment by psagrera** [comment]
If I use this mapping:
ipfix:

  mapping:
    - field: 137
      destination: CustomInteger_1
      penprovided: true
      pen: 2636

I got : 

"BgpCommunities":[],"AsPath":[],"HasMpls":true,"MplsCount":2,"Mpls_1Ttl":64,"Mpls_1Label":299792,"Mpls_2Ttl":64,"Mpls_2Label":299824,"Mpls_3Ttl":0,"Mpls_3Label":0,"MplsLastTtl":0,"MplsLastLabel":0,"MplsLabelIp":[],"ObservationDomainId":4194369536,"ObservationPointId":0,"CustomInteger_1":**402653541**,"CustomInteger_2":0,"CustomInteger_3":0,"CustomInteger_4":0,"CustomInteger_5":0,"CustomBytes_1":[],"CustomBytes_2":[],"CustomBytes_3":[],"CustomBytes_4":[],"CustomBytes_5":[]}

This number (**402653541**) corresponds to CPID value (357)- Ingress Interface details   

```
>>> decimal_num = 402653541
>>> hex_num = hex(decimal_num)
>>> mask = (1 << 17) - 1
>>> final_decimal_value = decimal_num & mask
>>> final_decimal_value
357
```
My problem is that it doesn't go through all the values 137 (it takes the last one).

**Comment by lspgn** [comment]
Would you be able to test the branch `mapping/lists` from #149?
With the config
```yaml
ipfix:
  mapping:
    - field: 137
      destination: CustomList_1
      penprovided: true
      pen: 2636
```

I am able to obtain

```json
{
    "Type": "IPFIX",
    "TimeReceived": 1679631936,
    "SequenceNum": 54943,

    "CustomList_1":
    [
        2048,
        201327193,
        268435456,
        335544320,
        402653541
    ]
}
```

**Comment by psagrera** [comment]
Hi Louis, 

It's working fine, thank you very much for the patch 

```
  "CustomList_1": [
    2048,
    201327190,
    268435456,
    335544320,
    402653542
  ]
}
```

**Comment by lspgn** [comment]
Merged to main

**Comment by lspgn** [comment]
@psagrera JFYI in the new v2 version #150 
https://github.com/netsampler/goflow2/blob/app/refactor/docs/protocols.md#map-custom-fields

You should be able to get the data inside protobuf and as text

An overview with the new configuration file:

```yaml
formatter:
  fields:
    - juniper_properties
  protobuf:
    - name: juniper_properties
      index: 1001
      type: varint
      array: true
ipfix:
  mapping:
    - field: 137 # Juniper Properties
      destination: juniper_properties
      penprovided: true # has an enterprise number
      pen: 2636 # Juniper enterprise
```
