### ISSUE TITLE
Destination mac address capture behavior

### ISSUE THREAD

**Issue by JargeZ** [netsampler/goflow2#15]
Hi, I'm not exactly sure if this is a bug or the correct behavior.
The issue is that when I capture flow of L2 traffic from my Nexus 6k, i get attribute DstMaс in proto is zero
![](https://i.imgur.com/fYvVWEW.png)
As I was able to determine, this is due to the fact that here
https://github.com/netsampler/goflow2/blob/88cbf5817281033c81123660446d31bdaffe10c1/producer/producer_nf.go#L254-L258
For dstMas, 57 type of field is used, while apparently 80 should be used

I changed this in my code, and now I get the correct mac-addresses.
```
// Mac
case netflow.NFV9_FIELD_IN_SRC_MAC:
  DecodeUNumber(v, &(flowMessage.SrcMac))
case netflow.NFV9_FIELD_IN_DST_MAC:
  DecodeUNumber(v, &(flowMessage.DstMac))
```
Please tell me if this is normal or why the original uses _Outgoing destination MAC address_ for the destination MAC address field

**Comment by lspgn** [comment]
Hello,
I don't think I was ever able to fully test the Mac in NetFlow/IPFIX implementation.
I assume IN vs OUT is dependent on when the sampling happened (ingress or egress).
So it could make sense to have

```
case netflow.NFV9_FIELD_IN_SRC_MAC:
  DecodeUNumber(v, &(flowMessage.SrcMac))
case netflow.NFV9_FIELD_IN_DST_MAC:
  DecodeUNumber(v, &(flowMessage.DstMac))
case netflow.NFV9_FIELD_OUT_SRC_MAC:
  DecodeUNumber(v, &(flowMessage.SrcMac))
case netflow.NFV9_FIELD_OUT_DST_MAC:
  DecodeUNumber(v, &(flowMessage.DstMac))
```

Which should work as expected unless the four fields are present in a single sample.
I'll make the change.

Thank you

**Comment by lspgn** [comment]
@JargeZ made #16, would you be able to have a look?
