### ISSUE TITLE
NetFlow5 Sampling Interval field should be split into Sampling Mode + Sampling Rate

### ISSUE THREAD

**Issue by AlexandreYang** [netsampler/goflow2#167]
Hi,

It seems that the NetFlow5 sampling_interval field is not decoded correctly when a Sampling Mode is set.

Based on this doc below, the sampling interval field should be parsed as "First two bits hold the sampling mode; remaining 14 bits hold value of sampling interval", but currently implement seems to be consider the whole field as sampling interval.

![image](https://github.com/netsampler/goflow2/assets/49917914/586c2ba3-6d0f-4120-ae70-d718cb6377cb)

https://www.cisco.com/c/en/us/td/docs/net_mgmt/netflow_collection_engine/3-6/user/guide/format.html

## Example 

Example pcap with sampling mode: https://github.com/Graylog2/graylog-plugin-netflow/blob/master/src/test/resources/netflow-data/netflow5.pcap

![image](https://github.com/netsampler/goflow2/assets/49917914/797a848b-55b6-4cc1-a97d-d73f8c3b2546)

The sampling_interval contains `0100000001100100`.
Currently, this is converted to `sampling_interval: 16484`
Instead of `sampling_interval: 100, sampling_mode:1`

---

I can try to come up with a fix PR if we agree this is an issue to fix.

**Comment by lspgn** [comment]
Hi @AlexandreYang 
Good catch, I'm missing a bit operation there

https://github.com/netsampler/goflow2/blob/f77d8832051b7462998b7eb19d4088a5c1f4b1f4/producer/producer_nflegacy.go#L67

I will do the fix in v2 and this.

Thank you

**Comment by lspgn** [comment]
Added in https://github.com/netsampler/goflow2/commit/d090ab3d7b59d98dd0ce6b39338809b2f849af5c
and #171
