### ISSUE TITLE
Dashboards enhancements

### ISSUE THREAD

**Issue by gaby** [netsampler/goflow2#169]
Are there any plans to enhance the dashboards? Or maybe someone can share their modified dashboards.

Things that I seen missing:
- Bandwidth
- Bytes column should be human readable
- List of top 10 protocols
- Support for selecting sources in the traffic dashboard (for when sending flows from different sources)

**Comment by lspgn** [comment]
You are more than welcome to share the Grafana dashboards with PRs. This is much appreciated.

For information: the compose stacks are not the main priority inside this repository. They provide a quick way to get started but are only a suggestion on how to build your flow collection pipeline.
Other projects focus on the front-end more.

**Comment by gaby** [comment]
I currently don't have any other dashboards. If anyone else does and doesnt mind sharing that would be great. :-) 

Or if there's a list of repos container pipelines/dashboards that also works

**Comment by prabhatsharma** [comment]
@gaby I published some dashboards earlier today for OpenObserve - https://github.com/openobserve/dashboards/tree/main/Netflow . I am working on a blog and will publish soon.

**Comment by gaby** [comment]
> @gaby I published some dashboards earlier today for OpenObserve - https://github.com/openobserve/dashboards/tree/main/Netflow . I am working on a blog and will publish soon.

@prabhatsharma Thank you! That looks awesome! 💪
