### ISSUE TITLE
BgpNextHop array - ip split by ,

### ISSUE THREAD

**Issue by mooneym17** [netsampler/goflow2#175]
BgpNextHop appears to spit the IP into an array

"BgpNextHop": [
        192,
        168,
        3,
        132
    ],

is this expected? I would have thought we should have:

"BgpNextHop": [
        192.168.3.132,
    ],

**Comment by lspgn** [comment]
Hello @mooneym17 
I will need a bit more information: what version, what CLI arguments are you passing?

**Comment by mooneym17** [comment]
@ispgn

sure, nothing special, just running the container as so: 

podman run --net host -d --name goflow2  goflow2:v1.3.4   -listen "netflow://:4738" -metrics.addr ":8091" -reuseport -transport "kafka"  -transport.kafka.brokers "127.0.0.1:9092" -transport.kafka.hashing -workers 1

**Comment by lspgn** [comment]
Will give it a try. Thank you for the report :) 

Would you be able to test out v2.0.0?
This may handle better formatting

**Comment by mooneym17** [comment]
hi ispgn, with version 2.0.0 , BGP nexthop appears to show as hex, ie: "bgp_next_hop":"5167df41"

**Comment by lspgn** [comment]
Hi @mooneym17,
Sorry for the delay.

In the `mapping.yaml` for v2, could you add the following:

```yaml
formatter:
  render:
    bgp_next_hop: ip
```

I realize this is listed [here](https://github.com/netsampler/goflow2/blob/main/docs/protocols.md#columns-and-renderers) but it's a bit hidden.

This said, as `bgp_next_hop` is a supported field, I will force the default renderer.

**Comment by mooneym17** [comment]
Great. That works.
