### ISSUE TITLE
Redhat OS Error `GLIBC_2.32' not found (required by goflow2)

### ISSUE THREAD

**Issue by rajasegaran89** [netsampler/goflow2#178]
I installed goflow2-1.3.4-1.x86_64.rpm in my redhat machine, when i execute it throws error as below:

$goflow2 -h
goflow2: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by goflow2)
goflow2: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by goflow2)

Can anyone help?

**Comment by lspgn** [comment]
Hello,
Which version of RedHat? You are missing an [important dependency](https://rpmfind.net/linux/rpm2html/search.php?query=libc.so.6(GLIBC_2.32)(64bit)) but I am not familiar with that OS.

You can build statically GoFlow2:

```bash
CGO_ENABLED=0 go build cmd/goflow2 -static
```

**Comment by rajasegaran89** [comment]
Hi @lspgn,
Im using Redhat 7.9.

**Comment by lspgn** [comment]
Actually you may be able to build it from the machine, this should solve any libc issues.

```
go build cmd/goflow2
```
