### ISSUE TITLE
ASN not include in data json

### ISSUE THREAD

**Issue by jsofari** [netsampler/goflow2#182]
hello, is there any other configuration to show asn in json data?
{
  "Type": "NETFLOW_V9",
  "TimeReceived": 1688118012,
  "SequenceNum": 16310,
  "SamplingRate": 0,
  "FlowDirection": 0,
  "SamplerAddress": "43.225.64.73",
  "TimeFlowStart": 1688118294,
  "TimeFlowEnd": 1688118294,
  "TimeFlowStartMs": 1688118293990,
  "TimeFlowEndMs": 1688118293990,
  "Bytes": 134,
  "Packets": 1,
  "SrcAddr": "103.247.216.203",
  "DstAddr": "103.116.201.22",
  "Etype": 2048,
  "Proto": 17,
  "SrcPort": 53,
  "DstPort": 52575,
  "InIf": 46,
  "OutIf": 30,
  "SrcMac": "dc:2c:6e:5a:d6:6a",
  "DstMac": "6e:c6:97:15:d5:0b",
  "SrcVlan": 0,
  "DstVlan": 0,
  "VlanId": 0,
  "IngressVrfId": 0,
  "EgressVrfId": 0,
  "IpTos": 0,
  "ForwardingStatus": 0,
  "IpTtl": 0,
  "TcpFlags": 0,
  "IcmpType": 0,
  "IcmpCode": 0,
  "Ipv6FlowLabel": 0,
  "FragmentId": 0,
  "FragmentOffset": 0,
  "BiFlowDirection": 0,
  "SrcAs": 00,
  "DstAs": 0,
  "NextHop": "103.182.46.5",
  "NextHopAs": 0,
  "SrcNet": 0,
  "DstNet": 0,
  "BgpNextHop": [],
  "BgpCommunities": [],
  "AsPath": [],
  "HasMpls": false,
  "MplsCount": 0,
  "Mpls_1Ttl": 0,
  "Mpls_1Label": 0,
  "Mpls_2Ttl": 0,
  "Mpls_2Label": 0,
  "Mpls_3Ttl": 0,
  "Mpls_3Label": 0,
  "MplsLastTtl": 0,
  "MplsLastLabel": 0,
  "MplsLabelIp": [],
  "ObservationDomainId": 0,
  "ObservationPointId": 0,
  "CustomInteger_1": 0,
  "CustomInteger_2": 0,
  "CustomInteger_3": 0,
  "CustomInteger_4": 0,
  "CustomInteger_5": 0,
  "CustomBytes_1": [],
  "CustomBytes_2": [],
  "CustomBytes_3": [],
  "CustomBytes_4": [],
  "CustomBytes_5": [],
  "CustomList_1": []
}

**Comment by lspgn** [comment]
Hello,
Could you give me more details: GoFlow2 version number, device model and version.
If your router is not sending AS data, this won't be featured in the JSON.

**Comment by jsofari** [comment]
i'am using juniper mx204, vyos and mikrotik. goflow latest version

**Comment by jsofari** [comment]
> Hello, Could you give me more details: GoFlow2 version number, device model and version. If your router is not sending AS data, this won't be featured in the JSON.
i'am using juniper mx204, vyos and mikrotik. goflow latest version

**Comment by jsofari** [comment]
> Hello, Could you give me more details: GoFlow2 version number, device model and version. If your router is not sending AS data, this won't be featured in the JSON.



i'am using juniper mx204, vyos and mikrotik. goflow latest version

**Comment by lspgn** [comment]
Would you be able to send me a packet capture?
Do all have a full BGP table attached?
