### ISSUE TITLE
Incorrect FragmentOffset parsing

### ISSUE THREAD

**Issue by vanyasvl** [netsampler/goflow2#184]
goflow2 is incorrectly parsing FragmentOffset field in IP packet
it takes 2bytes (16bits)
`fragOffset = binary.BigEndian.Uint16(data[offset+6 : offset+8])`
But the first thee bits are IP Flags and the only next 13bits are FragmentOffset

https://en.wikipedia.org/wiki/Internet_Protocol_version_4

As workaround you can do binary and with 8191 to clean Flags bits:

```
fragOffset = binary.BigEndian.Uint16(data[offset+6 : offset+8])
fragOffset = fragOffset & 8191
```

**Comment by lspgn** [comment]
Thank you! Will have a look

**Comment by lspgn** [comment]
Merged the fix. Thank you @vanyasvl
