### ISSUE TITLE
Incorrect sflow parsing TCP/UDP ports in case of IP fragment

### ISSUE THREAD

**Issue by vanyasvl** [netsampler/goflow2#185]
When sflow packet contains an IP fragment (FragmentOffset != 0), goflow still parses the srcPort and dstPort fields. This is incorrect because in such cases, the TCP/UDP header is missing, and garbage data ends up in the srcPort/dstPort fields.

Workaround:
```
if len(data) >= offset+4 && (nextHeader == 17 || nextHeader == 6)  && (fragOffset & 8191) == 0 {
			srcPort = binary.BigEndian.Uint16(data[offset+0 : offset+2])
			dstPort = binary.BigEndian.Uint16(data[offset+2 : offset+4])
		}
```

**Comment by lspgn** [comment]
Good catch! Will have a look. Thank you
