### ISSUE TITLE
Question: Does it support to sending data to kafka in json format?

### ISSUE THREAD

**Issue by Slepwin** [netsampler/goflow2#19]
Does it support to sending data to kafka in json format?

**Comment by lspgn** [comment]
Yes
Use CLI arguments
```
-format json -transport=kafka
```

**Comment by Slepwin** [comment]
Thanks Louis, one more question:  can i plug the stdin of the enricher to the stdout of GoFlow in json? or only protobuf supported?

**Comment by lspgn** [comment]
You would have to edit the code of the enricher. Only protobuf is supported for input, output can be json or protobuf on the other hand.
