### ISSUE TITLE
Support for Huawei 's netstream protocol

### ISSUE THREAD

**Issue by ChaoHsupin** [netsampler/goflow2#216]
netstream protocol define by Huawei, the  propocol is similar to netflow.

I config netflow channel in goflow2 , could receive some netstream udp packets，but only  a little receive, no all.

can we support for Huawei 's netstream protocol ?

reference: https://actfornet.com/ueditor/php/upload/file/20181230/1546124236332695.pdf

**Comment by lspgn** [comment]
Hi @ChaoHsupin,
I recall Netstream was a variant of a NetFlow so it should be supported.
Could you send me a packet capture?

Please provide also the version you're using, the CLI arguments and log messages.

Thank you

**Comment by ChaoHsupin** [comment]
@lspgn There may be a packet loss, has solved. thanks
