### ISSUE TITLE
Sarama changed from Shopify to IBM

### ISSUE THREAD

**Issue by bpereto** [netsampler/goflow2#228]
**Describe the bug**
The new location is: github.com/IBM/sarama which produces current resolving problems at build.

**Comment by lspgn** [comment]
Thank you
Will have a look

**Comment by lspgn** [comment]
I wasn't able to reproduce but made the change in #231 

Could you have a look @bpereto ?
What error were you getting?

**Comment by bpereto** [comment]
Strange, I will recheck at the next build.

**Comment by bpereto** [comment]
Ok, it seems to work now.
