### ISSUE TITLE
MaxMind country missing in KCG

### ISSUE THREAD

**Issue by fyzali** [netsampler/goflow2#230]
**Describe the bug**
MaxMind ASN field is working fine. Country field blank/empty in kcg. It is working fine with enricher in elk.

**To Reproduce**
ENTRYPOINT [ "/bin/bash", "-c", "./goflow2 -transport.file.sep= -format=bin | ./enricher  -db.asn=GeoLite2-ASN.mmdb -db.country=GeoLite2-Country.mmdb -transport.kafka.brokers=kafka:9092  -transport=kafka  -transport.kafka.topic=flows -format=bin"]

Added in compose/kcg/clickhouse/create.sh
        src_country String,
        dst_country String,

**Expected behavior**
source and destination field should not be empty.

**Captures**
![image](https://github.com/netsampler/goflow2/assets/7515332/7685b70e-c02b-4727-b0ae-a4d06b1fc4ce)

**GoFlow2:**
latest clone

**Comment by lspgn** [comment]
Hi @fyzali,
For your information, support for enrichment and compose is very limited. I invite you to have a look at [akvorado](https://github.com/akvorado/akvorado) for a more complete stack.

The enricher is not included in the current compose. I believe you need to make sure ClickHouse is aware of the proto defintion.
This can be changed inside docker-compose:

https://github.com/netsampler/goflow2/blob/76246841fb1684953c899f620088e426b29f49ff/compose/kcg/docker-compose.yml#L67

into:

```yaml
      - ../../cmd/enricher/pb/flowext.proto:/var/lib/clickhouse/format_schemas/flow.proto
```

ClickHouse will be aware of this field and will be able to map it to the correct column.

Another suggestion, without an enricher, would be to leave it to ClickHouse to map the country from a prefix into country/ASN. This can be done by obtaining the CSV file from MaxMind and using an [`ip_trie` dictionary](https://clickhouse.com/docs/en/sql-reference/dictionaries#ip_trie). This could be done upon insertion with the materialized view.

**Comment by lspgn** [comment]
@fyzali let me know if you are still experiencing issues. Otherwise will close this.
