### ISSUE TITLE
omit key from the messages produced  by goflow

### ISSUE THREAD

**Issue by alihossein** [netsampler/goflow2#244]
Hi. 
I'm using GoFlow and sending JSON data to a Kafka topic with 9 partitions. However, the data isn't being distributed evenly across the partitions, and some partitions have significantly less data than others.
Each message includes a key, and I want to remove this key from every message. Is there a way to achieve this?

> /goflow2 -listen sflow://127.0.0.1:6343 -workers=100 -transport.file.sep= -format=pb -format.protobuf.fixedlen=true | /enricher -db.asn="/GeoLite2-ASN.mmdb" -db.country="/GeoLite2-Country.mmdb" -transport=kafka -transport.kafka.brokers="kafka01.test:9092,kafka02.test:9092,kafka03.test:9092" -transport.kafka.topic="goflow"

and sample key is : 
`[94 152 151 50]-`

**Comment by lspgn** [comment]
Seems similar to #243.
Hoping to fix with #246

**Comment by lspgn** [comment]
Should be fixed on `main` branch. Let me know if still experiencing the problem.
