### ISSUE TITLE
NetFlow v9 - Codes/Types pretty-values

### ISSUE THREAD

**Issue by superstes** [netsampler/goflow2#245]
**Describe the bug**

I can't seem to find out why GoFlow2 does not resolve the types & codes (Etype, Proto, ...) of my flows to their 'pretty-values' (IPv4, TCP, ...).
Sorry if it's just a config issue - but I haven't found any information regarding this problem.

**To Reproduce**
1. Run GoFlow2:

   `/usr/local/bin/goflow2 -listen 'netflow://127.0.0.1:2055' -transport 'file' -transport.file '/var/cache/netflow_data.flowlog' -loglevel 'warn' -workers 2`

2. The codes & types are not resolved to 'pretty' values:

   ```json
   {"Type":"NETFLOW_V9","TimeReceived":1701698130,"SequenceNum":14,"SamplingRate":0,"FlowDirection":1,"SamplerAddress":"127.0.0.1","TimeFlowStart":1701697829,"TimeFlowEnd":1701697829,"TimeFlowStartMs":1701697828395,"TimeFlowEndMs":1701697828395,"Bytes":101,"Packets":1,"SrcAddr":"192.87.173.56","DstAddr":"138.201.123.137","Etype":2048,"Proto":17,"SrcPort":39918,"DstPort":53,"InIf":0,"OutIf":0,"SrcMac":"00:00:00:00:00:00","DstMac":"00:00:00:00:00:00","SrcVlan":0,"DstVlan":0,"VlanId":0,"IngressVrfId":0,"EgressVrfId":0,"IpTos":0,"ForwardingStatus":0,"IpTtl":0,"TcpFlags":0,"IcmpType":0,"IcmpCode":0,"Ipv6FlowLabel":0,"FragmentId":0,"FragmentOffset":0,"BiFlowDirection":0,"SrcAs":0,"DstAs":0,"NextHop":"","NextHopAs":0,"SrcNet":0,"DstNet":0,"BgpNextHop":[],"BgpCommunities":[],"AsPath":[],"HasMpls":false,"MplsCount":0,"Mpls_1Ttl":0,"Mpls_1Label":0,"Mpls_2Ttl":0,"Mpls_2Label":0,"Mpls_3Ttl":0,"Mpls_3Label":0,"MplsLastTtl":0,"MplsLastLabel":0,"MplsLabelIp":[],"ObservationDomainId":0,"ObservationPointId":0,"CustomInteger_1":0,"CustomInteger_2":0,"CustomInteger_3":0,"CustomInteger_4":0,"CustomInteger_5":0,"CustomBytes_1":[],"CustomBytes_2":[],"CustomBytes_3":[],"CustomBytes_4":[],"CustomBytes_5":[],"CustomList_1":[]}
    ```

**Expected behavior**
I would expect the values to be resolved to the ones listed in https://github.com/netsampler/goflow2/blob/main/producer/proto/render.go#L57 (EDIT: sorry - just saw that this file did not exist in the version I'm using)

Did I miss a config-flag? Or is this functionality not available in versions < 2.x?

The [`Getting started` information](https://github.com/netsampler/goflow2/tree/main#get-started) is showing these pretty-values by default.

**Sampler device:**
 - In my case `softflowd` is used to gather the flows:
   `/usr/sbin/softflowd -i 'any' -P 'udp' -n '127.0.0.1:2055' -v 9 -T 'full' -m 8192 -t 'expint=0'`

 - Version: 1.1.0
 - Estimated flow traffic: few hundred samples per minute (LAB environment)

**GoFlow2:**
 - Version: GoFlow2 v1.3.6 (2023-09-01T22:03:32+0000)
 - Environment: Debian package
 - OS: Debian 12 LVM

**Comment by superstes** [comment]
To keep it short: Is that kind of 'pretty-rendering' already supported in Version 1.3.x or was it just now implemented in Version 2.x?

**Comment by superstes** [comment]
No - I did not realize this flag could be used that way. The help-text is a little generic `List of fields to do keep in output`

My search for some information on how to use this flag did not yield any useful results. (_grepping over the repo and reading over the code in_ `format/* `) 


When I only provide `-format.selector 'EtypeName'` I get an empty JSON output.

Could you help me out with an example?

Edit:
I found some example after asking Google..
But the `*Name` fields seem to be ignored:

```
/usr/local/bin/goflow2 -listen netflow://127.0.0.1:2055 -format json -transport file -transport.file /var/cache/shieldwall/netflow_data.flowlog -loglevel warn -workers 2 -metrics.addr 127.0.0.1:9102 -format.selector TimeReceived,TimeFlowStartMs,TimeFlowEndMs,SequenceNum,FlowDirection,InIf,OutIf,SrcVlan,DstVlan,VlanId,Bytes,Packets,SrcAddr,DstAddr,Etype,EtypeName,Proto,ProtoName,SrcPort,DstPort,SrcMac,DstMac,IcmpType,IcmpCode,IcmpName,NextHop,IpTos,IpTtl,TcpFlags,ForwardingStatus,FragmentId,FragmentOffset

> {"TimeReceived":1701765004,"TimeFlowStartMs":0,"TimeFlowEndMs":0,"SequenceNum":11,"FlowDirection":0,"InIf":0,"OutIf":0,"SrcVlan":0,"DstVlan":0,"VlanId":0,"Bytes":46,"Packets":1,"SrcAddr":"79.124.x.x","DstAddr":"138.201.x.x","Etype":2048,"Proto":6,"SrcPort":40659,"DstPort":32602,"SrcMac":"00:00:00:00:00:00","DstMac":"00:00:00:00:00:00","IcmpType":0,"IcmpCode":0,"NextHop":"","IpTos":0,"IpTtl":0,"TcpFlags":2,"ForwardingStatus":0,"FragmentId":0,"FragmentOffset":0}
```

**Comment by lspgn** [comment]
Let me know if https://github.com/netsampler/goflow2/pull/250 fixes your issue. Will make a v1.3.7 afterwards.

**Comment by superstes** [comment]
Seems to work:

```
{"TimeReceived":1701853308,"Etype":2048,"EtypeName":"IPv4","Proto":6,"ProtoName":"TCP","IcmpType":0,"IcmpCode":0,"IcmpName":""}
```

**Comment by lspgn** [comment]
Tagged v1.3.7
