### ISSUE TITLE
`-transport.kafka.hashing=true` has no effect?

### ISSUE THREAD

**Issue by simPod** [netsampler/goflow2#248]
**Describe the bug**
_I have already mentioned it here https://github.com/netsampler/goflow2/issues/243#issuecomment-1836120093 but creating a new issue for better tracking_

**To Reproduce**
1. Run GoFlow2 with `-transport.kafka.hashing=true`

**Expected behavior**

`sarama.NewHashPartitioner` is the default value when I run goflow2.

![image](https://github.com/netsampler/goflow2/assets/327717/45c9686a-f09f-4a62-a22e-09bcd62fd9c1)

So assigning it here seems to have no effect:

https://github.com/netsampler/goflow2/blob/a1750f5f09737b0c9fb7e63b551e8d46607b8cf8/transport/kafka/kafka.go#L156

**GoFlow2:**
 - Version: v2

**Comment by lspgn** [comment]
Completed
