### ISSUE TITLE
convert the time_received_ns  value to second

### ISSUE THREAD

**Issue by alihossein** [netsampler/goflow2#262]
Hi. 
Is there a specific parameter or configuration option available to convert the **time_received_ns** value from nanoseconds to seconds?
I have carefully reviewed the documentation, but unfortunately, I couldn't locate any relevant information or guidance on the specified topic.

**Comment by lspgn** [comment]
Hi Ali,
Unfortunately no, only V1 of GoFlow2 is in second.
Could you indicate your use-case?
