### ISSUE TITLE
decode netflowv5 is ok,but decode netflowv5 exception:

### ISSUE THREAD

**Issue by fenggolang** [netsampler/goflow2#265]
run  goflow2: 
`
docker rm -f goflow2
docker run -d --name goflow2 \
        -p 8080:8080 \
	-p 16343:6343/udp \
	-p 9001:2055/udp \
	 netsampler/goflow2:3f017c4-amd64
`
decode netflowv5 is ok,but decode netflowv5 exception:

time="2023-12-18T12:30:16Z" level=warning msg="template error" blocking=false count=1 error="receiver: message from [::ffff:10.60.1.15]:40000 NetFlowV9 [version:9 type:Decode obsDomainId:2064641: templateId:1315] Error template not found" hostname= port=2055 queue_size=1000000 scheme=netflow workers=2

<img width="1764" alt="image" src="https://github.com/netsampler/goflow2/assets/16982786/6202ad99-d3b6-4007-a61f-35af9d3cda77">

**Comment by lspgn** [comment]
Hello,
Please use the template when reporting a bug.


Make sure you are not sending netflow v5 on an IPFIX/netflowv9 port or vice versa. You need to change the listening address to:
`-listen flow://:2055`
You will be able to also decide sflow on this port.

This said, the error indicates no template was found: you need to wait enough time to collect all templates. This is just a warning. It can be ignored and muted with `-loglevel error`
There are new changes to reduce the amount of log generated.

**Comment by lspgn** [comment]
Closing due to no response
