### ISSUE TITLE
v2.0.0 or v1.3.x

### ISSUE THREAD

**Issue by mmynk** [netsampler/goflow2#267]
The repo had a v2 release in August, however the later releases are all v1.3.x.

If I had to use the latest release, should I choose v2.0.0 or v1.3.7?

**Comment by lspgn** [comment]
Hello,
I'm waiting for some perf feedback before cutting a new 2.x release. If you can, build the latest in main.
2.x changes heavily vs 1.3.x and is now considered legacy.

**Comment by mmynk** [comment]
Thanks, that's helpful. So if i understand correctly, main is working on top of v2.0.0?

**Comment by lspgn** [comment]
Correct, many bug fixes and features have been integrated since the 2.0.0

**Comment by mmynk** [comment]
Thanks!
