### ISSUE TITLE
dbeaver connect clickhouse 8123,open default.flows table is error

### ISSUE THREAD

**Issue by fenggolang** [netsampler/goflow2#268]
![image](https://github.com/netsampler/goflow2/assets/16982786/49ea84b3-0ebe-4ead-b12e-f19eec6d5d0b)

**Comment by lspgn** [comment]
Hi
Please add a description and follow bug report template.
Furthermore this is a ClickHouse error message and it's part of the compose setup but I'm providing limited support. Priority is given to decoders bugs.
