### ISSUE TITLE
docker-compose up kcg,but grafana no data

### ISSUE THREAD

**Issue by fenggolang** [netsampler/goflow2#270]
when I up kcg by docker-compose,but open grafana,not data(clickhouse database have data)
<img width="1704" alt="image" src="https://github.com/netsampler/goflow2/assets/16982786/94798e2c-20da-4128-8626-7e9bd27676b0">

![image](https://github.com/netsampler/goflow2/assets/16982786/8c6ca723-21e1-4224-93ce-614b89f32eb1)

<img width="1250" alt="image" src="https://github.com/netsampler/goflow2/assets/16982786/c680979e-03cf-446b-b8e9-c654b8a6b1bf">

![image](https://github.com/netsampler/goflow2/assets/16982786/9a1651a3-1536-4dd9-aeeb-6fee60c1b586)

**Comment by lspgn** [comment]
Hi
For the third time, please use the bug report template.
This is part of the compose setup: I'm providing limited support. Priority is given to decoders bugs.

Your sampling rate is equal to zero. You need to remove the `*sampling_rate` from the query or make sure the decoder gets the sampling rate information.
