### ISSUE TITLE
Format bin not found

### ISSUE THREAD

**Issue by Luke-Williams9** [netsampler/goflow2#274]
**Describe the bug**
Trying to run goflow2 via docker-compose kcg stack. Goflow2 gives me a fatal error 'Format bin not found'
This happens regardless of whether I use your original docker-compose.yml which builds goflow2, or if I use the netsampler/goflow2:latest uploaded a few days ago.

**To Reproduce**
git clone https://github.com/netsampler/goflow2.git
cd goflow2/compose/kcg
sudo docker-compose up

**GoFlow2:**
 - Version: latest
 - Environment: Docker, 20.10.24+dfsg1
 - OS: Debian 12

**Comment by lspgn** [comment]
Hi Luke,
Thank you for raising this bug
What's your architecture? Arm/amd64?

**Comment by Luke-Williams9** [comment]
Hi Louis,

I'm running this on amd64 currently. I can also test it on a raspberry Pi 4 if that would help.



Luke Williams | ***@***.***

¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯

Senior Technician | Global Storm IT Corporation

Phone: (867) 873-8611

Email: ***@***.***

________________________________

**Comment by lspgn** [comment]
How did you install docker?
Version 20 seems old

https://docs.docker.com/engine/install/debian/

**Comment by Luke-Williams9** [comment]
Ok, I've updated docker to a current version 24.0.7, and used **netsampler/goflow2:v2.1.1** in my docker-compose.yml. It appears to be working now.

I always knew debian was conservative with updating their repos, but I never thought they'd have a version of docker 4 major versions behind :D

Thanks for your help.

**Comment by Luke-Williams9** [comment]
can close this now.
