### ISSUE TITLE
HTTP JSON output

### ISSUE THREAD

**Issue by prabhatsharma** [netsampler/goflow2#276]
Thanks for building and maintaining this, folks.

How do I send HTTP JSON output to an HTTP endpoint. I am trying to get goflow2 to send data to OpenObserve for analysis

**Comment by lspgn** [comment]
Hello,
This is not supported in GoFlow2.
You may be able to achieve this using tools like Vector:
stdin or file as source
And http as sink
https://vector.dev/docs/reference/configuration/sinks/http/

Let me know how this goes.

**Comment by prabhatsharma** [comment]
Added a https://github.com/netsampler/goflow2/pull/278 to support this. Let me know what you think.
