### ISSUE TITLE
enricher mismatching end group marker

### ISSUE THREAD

**Issue by freedomwarrior** [netsampler/goflow2#28]
Hello!
I'm trying to map IP to AS with enricher, but got this errors:
```
ERRO[0002] unexpected EOF                               
ERRO[0002] proto: invalid field number                  
ERRO[0002] proto: mismatching end group marker          
ERRO[0002] unexpected EOF                               
ERRO[0002] proto: invalid field number                  
ERRO[0002] proto: mismatching end group marker          
ERRO[0002] unexpected EOF                               
ERRO[0002] proto: invalid field number                  
ERRO[0002] proto: mismatching end group marker          
ERRO[0002] unexpected EOF                               
ERRO[0002] proto: invalid field number     
```             
GoFlow2 v1.0.4 (2021-06-12T16:48:35+0000)

I run this pipe as follow:
`goflow2 -format=pb | ./enricher -db.asn=/var/lib/geoip/GeoLite2-ASN.mmdb -db.country=/var/lib/geoip/GeoLite2-Country.mmdb`

And if I understand correctly, the full pipe must look like this, if I want to map IP to AS:
  **sflow_stream -> goflow2 -> enricher -> kafka -> ch**
Am I correct?

**Comment by lspgn** [comment]
Pipe is correct. I would advise to write an enricher that consumes from Kafka as well instead of using a pipe if you have a lot of flows.

Per [#105](https://github.com/cloudflare/goflow/issues/105#issuecomment-901498978) I believe this is resolved (use for GoFlow2`-format.protobuf.fixedlen=true`).
Will close, feel free to reopen/create a new issue if you have more questions.

**Comment by lspgn** [comment]
@freedomwarrior would you be able to test the `bug/enricher-decode` branch? You can get the binary artifacts from [here](https://github.com/netsampler/goflow2/runs/3451330796).

The command is 
```
$ goflow2 -transport.file.sep= -format=pb -format.protobuf.fixedlen=true | enricher 
```

This indicates to not add a `\n` at the end of the line since protobuf payload is prefixed by length and enricher can decode it now.

**Comment by freedomwarrior** [comment]
> @freedomwarrior would you be able to test the `bug/enricher-decode` branch? You can get the binary artifacts from [here](https://github.com/netsampler/goflow2/runs/3451330796).
> 
> The command is
> 
> ```
> $ goflow2 -transport.file.sep= -format=pb -format.protobuf.fixedlen=true | enricher 
> ```
> 
> This indicates to not add a `\n` at the end of the line since protobuf payload is prefixed by length and enricher can decode it now.

I test it, but no luck:
```
ERRO[0004] proto: mismatching end group marker
ERRO[0004] proto: invalid field number
ERRO[0004] proto: mismatching end group marker
ERRO[0004] proto: invalid field number
ERRO[0004] proto: mismatching end group marker
ERRO[0004] proto: invalid field number
ERRO[0004] proto: mismatching end group marker
ERRO[0004] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] unexpected EOF
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
ERRO[0005] proto: mismatching end group marker
ERRO[0005] proto: invalid field number
```
```

goflow2 -v
GoFlow2 v1.0.4-7-gc107b6b (2021-08-28T17:28:23+0000)
```

Run as follow:
`# goflow2 -transport.file.sep= -format=pb -format.protobuf.fixedlen=true | ./enricher`

**Comment by lspgn** [comment]
I'll keep investigating. Have you built the enricher as well on this particular branch?

**Comment by freedomwarrior** [comment]
> Have you built the enricher as well on this particular branch?
> 
> Edit: I tested replaying your packet with both GoFlow2 and the enricher on commit `gc107b6b` and it correctly decodes
> 
> ```shell
> $ tcprewrite -i capture.pcap -o capture-mod.pcap -D 195.78.39.140:192.168.x.x --enet-dmac=test-machine-mac
> $ tcpreplay -i interface capture-mod.pcap
> ```

It works!
First time I only use goflow2 binary from artifacts.
I try to build both enricher and goflow2 from `bug/enricher-decode` branch and all good.

**Comment by lspgn** [comment]
I merged to `main`, will make sure new options are good and then will make a release.
Thank you for reporting the issue!
