### ISSUE TITLE
level=fatal msg="Format bin not found"

### ISSUE THREAD

**Issue by qhz-redes** [netsampler/goflow2#286]
Good morning, I'm trying to use goflow2 with kafka and clickhouse, kcg model, but when I run docker I receive the following error message:

goflow2-1 | time="2024-02-06T12:26:25Z" level=fatal msg="Format bin not found"

As this error message is displayed, the application does not perform any collection, nothing appears in grafana. How can I go about using it? Taking advantage of how can I enrich the bank with geolocation?
![Screenshot_20240206_094142](https://github.com/netsampler/goflow2/assets/125511907/2dcd5ec8-64e1-4f23-8c45-79dc7949147d)

**Comment by ACodingfreak** [comment]
Any update regarding this issue ? I am seeing the same error.

**Comment by lspgn** [comment]
Thank you for pointing this out. A fix is coming with #299.
A change in the docker build process resulted in no `latest` tag pushed. It was still on a v1 version.
You'll need to manually `docker-compose pull` after this is fixed.
