### ISSUE TITLE
Externalising template cache

### ISSUE THREAD

**Issue by shyam334** [netsampler/goflow2#29]
The feature request is to have the ability to externalise the template cache, 
such that when goflow restarts, it can immediately pick up the cache and serve the data. (minimising recovery time)

As an extension, perhaps we could use the mechanism to create a HA solution,
but I'd think that's a seperate piece of work.

Noticed that there is [already some work done in the related area](https://github.com/netsampler/goflow2/blob/e52a053c9cf8026ac9c36f68ff4434bf80b4e287/cmd/goflow2/main.go#L55
).

What are your thoughts.

P.S.
Great to see the project being actively developed!

**Comment by lspgn** [comment]
Hi @shyam334 
Yes that is a good idea. What backend implementation are you thinking of? Besides local files, maybe Redis could do?
Along with this, expiration of templates should be added.

The endpoint you found was more for debugging and haven't had time to migrate it during the move to GoFlow2.

**Comment by shyam334** [comment]
Redis and files sounds good.
And yeah, all the caveats that comes with caching.

Noticed some mention of expiry in https://datatracker.ietf.org/doc/html/rfc5153#section-6.2 .

**Comment by lspgn** [comment]
For #49 I went with a similar design I used with Format and Transports.
Right now there is only a sample with [Memory](https://github.com/netsampler/goflow2/blob/feature/modularize-templates/decoders/netflow/templates/memory/memory.go) which could be used as a base for a file/http/redis (warm memory up with cached data during `Init` then push to cache every time an update is added)

Not sure how much time I'll have to do a Redis template module but happy to merge some PRs.

**Comment by lspgn** [comment]
I believe this is solved in v1.2.1
