### ISSUE TITLE
Reception of multicast messages does not work

### ISSUE THREAD

**Issue by stm32repo** [netsampler/goflow2#290]
GoFlow2 v2.1.2
debian 12, kvm.

run: /opt/goflow2/goflow2 -listen "netflow://224.0.1.202:2055" -transport kafka -transport.kafka.brokers localhost:9092 -transport.kafka.topic goflow2 -transport.kafka.version 3.6.0 -loglevel debug

agent: /usr/sbin/softflowd -i br0 -p /run/softflowd/br0.pid -c /run/softflowd/br0.ctl -v 10 -6 -t general=15 -t maxlife=30 -N -P udp -n 224.0.1.202:2055 -S br0

**Comment by lspgn** [comment]
Hello,
This is not currently supported.
Also please use the correct template when filing issues.

Thank you
