### ISSUE TITLE
Feature: Rotate file output on SIGHUP

### ISSUE THREAD

**Issue by SuperQ** [netsampler/goflow2#3]
In order to support log rotation, it would be nice if the file transport would close and open the log file on SIGHUP. 

Something like https://github.com/nytimes/logrotate/ could be used.

**Comment by lspgn** [comment]
This is a good idea.
Two questions:
So on SIGHUP, does it block and then on second SIGHUP starts sending again?
When dumping to stdout, this could be handled by journald? Shouldn't this be preferred?

**Comment by SuperQ** [comment]
Typically a single SIGHUP is what is done, it only blocks for long enough to close and reopen the file. This is only needed for when a filename is used, not stdout.

The process for external log rotation looks something like this:
* mv /path/to/logfile /path/to/logfile.bak
* SIGHUP
* PID stops writing to  /path/to/logfile.bak
* PID starts writing to new  /path/to/logfile

For stdout, there's no reason as you're correct, journald deals with this.

**Comment by lspgn** [comment]
Are you able to test this branch?
Binaries should be in the artifacts.

**Comment by SuperQ** [comment]
Sorry, I totally missed the request to test it. I'll give it a test this weekend.
