### ISSUE TITLE
Bad values time_flow_start_ns, time_flow_end_ns when sending Newflow v5 to collector

### ISSUE THREAD

**Issue by honzakolarik** [netsampler/goflow2#303]
**Describe the bug**
The goflow2 collector decodes badly the values of fields time_flow_start_ns and time_flow_end_ns in my case approximately 20 days ago.

**To Reproduce**
1. Start softflowd -i tun0 -n 10.123.10.1:2055 -v 5 -D
2. Start goflow2: /opt/goflow2 -listen netflow://10.123.10.1:2056 --format bin -transport.kafka.brokers=10.4.4.2:9092 -transport=kafka -transport.kafka.topic=goflow2
3. Then in clickhouse database I can observe bad values in the columns time_flow_start_ns and time_flow_end_ns. The values are approximatelly 20 days ago.

**Expected behavior**
I expect correct values of time_flow_start_ns and time_flow_end_ns. The original https://github.com/cloudflare/goflow project shows correct values (although sub second resolution is missing). As well as wireshark and nfdump collector decode flow times correctly.

**Sampler device:**
 - Brand: softflowd on linux
 - Version: softflowd/focal,now 1.0.0-2 from Ubuntu 20.04
 - Estimated flow traffic: 1000 samples per second, but doesn't matter, I don't have performance problem

**GoFlow2:**
 - Version: 2.1.3-0-gc109a5f
 - Environment: binary compiled by go version go1.22.1 linux/amd64 on Linux Ubuntu Server 20.04, running without any dockers or kubernetes
 - OS: Linux Ubuntu Server 20.04

**Additional context**
I did this change and values are correct for me:
<pre>
honza@kcg:~/goflow2$ git diff producer/proto/producer_nflegacy.go
diff --git a/producer/proto/producer_nflegacy.go b/producer/proto/producer_nflegacy.go
index 67a2039..1e80aa6 100644
--- a/producer/proto/producer_nflegacy.go
+++ b/producer/proto/producer_nflegacy.go
@@ -13,8 +13,8 @@ func ConvertNetFlowLegacyRecord(flowMessage *ProtoProducerMessage, baseTime uint
 
        timeDiffFirst := (uptime - record.First)
        timeDiffLast := (uptime - record.Last)
-       flowMessage.TimeFlowStartNs = baseTime - uint64(timeDiffFirst)*1000000000
-       flowMessage.TimeFlowEndNs = baseTime - uint64(timeDiffLast)*1000000000
+       flowMessage.TimeFlowStartNs = baseTime - uint64(timeDiffFirst)*1000000
+       flowMessage.TimeFlowEndNs = baseTime - uint64(timeDiffLast)*1000000
 
        v := make([]byte, 4)
        binary.BigEndian.PutUint32(v, uint32(record.NextHop))
</pre>

**Comment by lspgn** [comment]
Hi @honzakolarik 
Good catch, after checking, it seems uptime/first/last are in milliseconds

https://github.com/netsampler/goflow2/blob/c109a5f2c6889761f936e7f1c29389dd52d81129/producer/proto/producer_nflegacy.go#L59

Your patch fixes it

Thank you
