### ISSUE TITLE
Clickhouse Compose example results in corrupt data

### ISSUE THREAD

**Issue by johnkeates** [netsampler/goflow2#308]
**Describe the bug**
Using the example compose configuration seems to have some decoding issues, src, dst, sampler are all decoded into seemingly random binary data.

**To Reproduce**
1. Run the compose kcg example
2. Check the contents of clickhouse
3. See error

**Expected behavior**
Complete decoded protobuf messages in Clickhouse

**Captures**
Standard NetFlow v9 from Palo Alto (https://docs.paloaltonetworks.com/pan-os/11-0/pan-os-admin/monitoring/netflow-monitoring/netflow-templates#ide31a0d85-0a89-430b-8fe8-c13280d58e58)

**GoFlow2:**
 - Version: v2.1.3
 - Environment: Docker
 - OS: Linux Ubuntu Server Jammy

**Additional context**
The ELK example does work, checking NetFlow9 packet captures shows correct flows, doing JSON text outputs also shows correct data. Haven't checked the raw contents of Kafka yet.

**Comment by johnkeates** [comment]
<img width="1072" alt="Screenshot 2024-04-06 at 15 29 01" src="https://github.com/netsampler/goflow2/assets/5306980/99203f33-41f7-47b1-9910-01af8ecf0f50">

**Comment by lspgn** [comment]
Hello,
ClickHouse stores the addresses in their binary form. When you query, you need to use specific functions to output text. This is for performance reasons.

Example with the query you can find in Grafana:

https://github.com/netsampler/goflow2/blob/1b390e4c28c1cc49f016356cf09e26e71aa0f4ac/compose/kcg/grafana/dashboards/viz-ch.json#L201

**Comment by johnkeates** [comment]
That's what I assumed at first, but since the Dashboards aren't providing data either something must be going wrong. But now that you point it out, browsing the raw tables in Clickhouse isn't exactly the way to go (I don't have much experience with it).

I'll see if I can use the Grafana query inspector to find out what is going wrong, since the flows and flow contents are present and correct on the wire.

**Comment by johnkeates** [comment]
So it looks like the query goes through just fine but simply returns a series of sumbytes that are all 0. Perhaps the issue is related to the timestamps being a bit iffy (they are in NS but the start/end and collected are at different resolutions).

The data is present so something must be going wrong in either the query itself or the presentation in the dashboard:

<img width="450" alt="Screenshot 2024-04-06 at 18 53 30" src="https://github.com/netsampler/goflow2/assets/5306980/8bd524bc-fd9f-488b-bd96-4adae9cd13ad">
<img width="778" alt="Screenshot 2024-04-06 at 18 55 38" src="https://github.com/netsampler/goflow2/assets/5306980/4c73e2b9-4942-465b-a35a-25748554c4e3">



But hey, at least it's not a complete compose bug, that's good to know. Now to figure out what is actually going wrong.

**Comment by johnkeates** [comment]
I feel like I'm rubberducking via GitHub issues, sorry about that 😶‍🌫️ It's a simple matter of the Palo Alto devices not supporting sampling, but the queries assuming sampling is available. Because sampling_rate is always 0 it multiplies the bytes by 0. A quick edit of the query removing the sampling factor solves that.

**Comment by xobs** [comment]
Because I ran into this issue as well (EdgeRouter POE-5 from Ubiquiti also doesn't seem to store `sampling_rate`), and I'm unfamiliar with this tooling, I thought I'd post how to work around this.

To edit the query for each panel, click on the menu then go to `Inspect -> Panel JSON`. Scroll down to `targets.query` and remove any instance of `sampling_rate`.

![Image](https://github.com/user-attachments/assets/d4984a04-36ca-4f57-9701-6a2d7fbd3da7)

**Comment by xobs** [comment]
This could actually be fixed by replacing the default query such that it doesn't ever multiply by "0":

Existing:
```
SUM(bytes * sampling_rate)
```

New:
```
SUM(bytes * CASE WHEN sampling_rate = 0 THEN 1 ELSE sampling_rate END)
```

Though I haven't done any performance analytics. Still, if both of us have run into the same issue, it might be worth fixing.

Another option, of course, is to make it so that `sampling_rate` is never zero in the database.

**Comment by xobs** [comment]
My settings all got reverted overnight, so I think you need to go to /traffic-clickhouse?editview=dashboard_json and edit it there.
