### ISSUE TITLE
How to differentiate between IPv4 and IPv6 address of the sampler?

### ISSUE THREAD

**Issue by amarao** [netsampler/goflow2#31]
I looked into code, and it seems that goflow2 just collapses both into byte-array without any differentiation between IPv4 and IPv6 addresses. When data are read from (f.e.) Kafka, ipv4 addresses are mapped into random parts of IPv6 numbering plan, and there is no reliable way to separate them.

May be a flag for address family can help?

**Comment by saymonaraujo** [comment]
You can use `EType` to do this.

**Comment by lspgn** [comment]
I second what @saymonaraujo says, the `EType` field is the flag for the address family.

IPv4 will either be 4 bytes or can be mapped inside of a 16 bytes IPv6 like: `::ffff:0102:0304`.

Will close. Feel free to reopen if you have more questions
