### ISSUE TITLE
Discussion - Using this project as a basis for an Otel Receiver

### ISSUE THREAD

**Issue by dlopes7** [netsampler/goflow2#310]
Hello @lspgn 

Sorry about opening an issue for this, it is more of a discussion.

I would be interested to hear your thoughts about using this collector as a basis for an [Opentelemetry Receiver](https://opentelemetry.io/docs/collector/architecture/#receivers).

Have you ever considered something like that? We are interested in writing a Netflow/Sflow/etc receiver and you obviously already have the performance and collection capabilities in this project.

It would be based around logs, treating the sample as a log entry (since it doesn't fit the contract for a span or metrics)

Eventually contributing it to the [list of receivers in otel](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver)

Interested in knowing your thoughts around this

**Comment by lspgn** [comment]
Hi @dlopes7,
This is a great idea, thank you. I've noticed that GoFlow2 is already used by datadog-agent and telegraf.
I'm seeing [Golang OTEL libraries](https://opentelemetry.io/docs/languages/go/) for logs are still in development: would it be viable?
Could the custom mapping be passed through an OTEL configuration?
I personally would not have enough time to build such thing though.

**Comment by dlopes7** [comment]
Thanks, I don't expect you to build this, but it sounds feasible to use this project or  parts of it as a otel receiver

Logs are indeed in alpha, but there are so many log receivers and exporters, I think it is worth it to implement as it matures.

I will do some more research and try to contribute, will tag you eventually if you are interested in taking a look!
