### ISSUE TITLE
NATS integration

### ISSUE THREAD

**Issue by udf2457** [netsampler/goflow2#311]
At the moment you have integration with Kafka.

[NATS](https://nats.io/) is a platform that is getting increasing adoption as an easier to deploy and manage alternative to Kafka.

It would be fantastic if you had support for NATS.

Whilst NATS does have MQTT support, it is [only there as an "enabling technology" for integration with legacy IoT deployments.  The NATS recommendation is to use NATS throughout and not rely on the MQTT bridge for greenfield deployments](https://docs.nats.io/running-a-nats-service/configuration/mqtt).

NATS is written in Go, so it has first-class support for Go integration with an [official client library](https://pkg.go.dev/github.com/nats-io/nats.go).

**Comment by lspgn** [comment]
Hello,
Thank you for your suggestion.
This has been proposed [before](https://github.com/netsampler/goflow2/pull/131).
Unfortunately, there is not enough time to maintain various possible implementations of message brokers (AMQP, MQTT, Kafka, Pulsar...).
GoFlow2 is mostly meant to decode various samples format and transform them into logs/events. I would suggest piping to Vector that will support many more protocols.
