### ISSUE TITLE
Goflow LoadBalace traffic not working 

### ISSUE THREAD

**Issue by majid-darvishfard** [netsampler/goflow2#331]
hi 
Why is the load not divided among the sockets, and one of the sockets is always queued?
![Screenshot from 2024-06-08 11-09-37](https://github.com/netsampler/goflow2/assets/46423765/bd4cb993-cff4-479b-b3ff-0fcaa7babb7e)

**Comment by lspgn** [comment]
Hello @majid-darvishfard,
Could you use the issue template? I am missing a lot of information to be able to help.
Please provide Linux kernel version, GoFlow2 version, command-line...

**Comment by majid-darvishfard** [comment]
hi  @lspgn 
I created Docker image from commit 7265159 branch master, 
my OS is :  Debian12      kernel:  6.1.27-1 (2023-05-08) x86_64 GNU/Linux
docker version : 26.1.3

And I use the following option to run goflow:
`'-addr "10.10.48.159:8082" -listen "netflow://10.10.31.31:5678/?count=10&workers=20&blocking=true&queue_size=10000" -err.cnt 1  -format "bin" -transport "kafka" -transport.kafka.brokers "10.10.48.132:9092,10.10.48.133:9092,10.10.48.134:9092" -transport.kafka.compression "gzip" -transport.kafka.flushbytes 104857600 -transport.kafka.flushfreq 5s -transport.kafka.maxmsgbytes 1000000  -transport.kafka.topic "netflow"`

**Comment by lspgn** [comment]
Sorry for the delay

What's the amount of flows per second?

Have a look at: https://github.com/netsampler/goflow2/blob/main/docs/performance.md
Try without blocking mode

**Comment by lspgn** [comment]
@majid-darvishfard let me know if your issue is solved. Otherwise will close.
