### ISSUE TITLE
filter incoming traffic  

### ISSUE THREAD

**Issue by majid-darvishfard** [netsampler/goflow2#334]
hi guys
Is it possible to filter incoming traffic in goflow2 before sending it to Kafka?
For example, let's send only Netflow packets whose DIRECTION value is 1

**Comment by lspgn** [comment]
Hello,
This is not possible.
Adding such filters would complicate a lot the code. I would suggest filtering once decoded (in Kafka using tools like vector or at query time in ClickHouse).
