### ISSUE TITLE
[SFlow] Throws away src/dst addr

### ISSUE THREAD

**Issue by simPod** [netsampler/goflow2#346]
**Describe the bug**
v2.1.5 is fine. v2.2.0 gives me empty dst_addr and src_addr sflow fields

**To Reproduce**
1. goflow2-2.2.0 -format=text -listen "sflow://:8900?count=24" -addr :8090
2. Receive samples '....'
3. See error

**Expected behavior**

**Captures v2.2.0**

```
type=SFLOW_5 time_received_ns=1724073211239028359 sequence_num=2900053160 sampling_rate=11111 sampler_address=8.9.0.29 time_flow_start_ns=1724073211239028359 time_flow_end_ns=1724073211239028359 bytes=1494 packets=1 src_addr= dst_addr= etype= proto=HOPOPT src_port=0 dst_port=0 in_if=1000200 out_if=1000150 src_mac=00:00:00:00:00:00 dst_mac=00:00:00:00:00:00 src_vlan=203 dst_vlan=250 vlan_id=0 ip_tos=0 forwarding_status=0 ip_ttl=0 ip_flags=0 tcp_flags=0 icmp_type=0 icmp_code=0 ipv6_flow_label=0 fragment_id=0 fragment_offset=0 src_as=0 dst_as=0 next_hop=1.2.3.4 next_hop_as=0 src_net=invalid Prefix dst_net=invalid Prefix bgp_next_hop= bgp_communities=[] as_path=[] mpls_ttl=[] mpls_label=[] mpls_ip=[] observation_domain_id=0 observation_point_id=0 layer_stack=[] layer_size=[] ipv6_routing_header_addresses=[] ipv6_routing_header_seg_left=0
```

**Captures v2.1.5**

```
type=SFLOW_5 time_received_ns=1724073326728783781 sequence_num=2900072682 sampling_rate=11111 sampler_address=8.9.0.29 time_flow_start_ns=1724073326728783781 time_flow_end_ns=1724073326728783781 bytes=1438 packets=1 src_addr=3.0.15.49 dst_addr=4.29.6.7 etype=IPv4 proto=TCP src_port=443 dst_port=57333 in_if=1000016 out_if=1000200 src_mac=9c:9a:ab:c6:61:c6 dst_mac=a1:ff:f7:55:36:3d src_vlan=106 dst_vlan=106 vlan_id=0 ip_tos=0 forwarding_status=0 ip_ttl=61 ip_flags=2 tcp_flags=24 icmp_type=0 icmp_code=0 ipv6_flow_label=0 fragment_id=29597 fragment_offset=0 src_as=0 dst_as=0 next_hop=169.150.194.65 next_hop_as=0 src_net=anon dst_net=anon bgp_next_hop= bgp_communities=[] as_path=[] mpls_ttl=[] mpls_label=[] mpls_ip=[] observation_domain_id=0 observation_point_id=0
```

**Sampler device:**
 - Brand: [Arista]
 - Model: [🤷🏾‍♀️]
 - Version: [e.g. 22]
 - Estimated flow traffic: [🤷🏾‍♀️]

**GoFlow2:**
 - Version: v2.0.0
 - Environment: Debian package
 - OS: Debian 12

**Additional context**

**Comment by simPod** [comment]
What I'm seeintg is that like every packet is determined as proto=HOPOPT with v2.2.0 but that's not the case with 2.1.5. [There have been some proto related changes](https://github.com/netsampler/goflow2/compare/v2.1.5...v2.2.0) in this version.

![image](https://github.com/user-attachments/assets/781ab85c-1ee7-44a7-a0e0-a5798cd42649)

**Comment by simPod** [comment]
Since HOPOPT is the first proto in the map I have a sneaking suspicion 😄  https://github.com/netsampler/goflow2/commit/6f075d6d35371bbcd64c499963d9760f8946d0a9#diff-899b9f22d784eeffcc32c564e39e6a79d8f837de77a8629d70376e9e6af3a009R64

**Comment by lspgn** [comment]
@simPod thank you for the bug report

are the packets encapsulated?

**Comment by lspgn** [comment]
Sorry! Introduced a bug and did not properly test.
Should be fixed now

**Comment by simPod** [comment]
Works like a charm! Thx
