### ISSUE TITLE
Add support for NATS JetStream

### ISSUE THREAD

**Issue by mfreeman451** [netsampler/goflow2#359]
**Is your feature request related to a problem? Please describe.**
Add support for the NATS JetStream message broker. 

**Describe the solution you'd like**
New code that adds support for NATS JetStream as a transport.

**Describe alternatives you've considered**
N/A

**Additional context**
NATS JetStream is a modern, fast, and efficient message-broker that can run anywhere, including the edge, or embedded into existing go-based software. Adding support for this popular message broker will open up new use-cases for goflow2 users.

**Comment by lspgn** [comment]
Hello,
Thank you for the feature request, I appreciate hearing from the users. Unfortunately this has been suggested before #311 and #131.
I don't have enough bandwidth to write, test and maintain a new message broker implementation.
I would suggest piping the output to a tool like [Vector](https://vector.dev/docs/reference/configuration/sinks/nats/).

**Comment by mfreeman451** [comment]
Would you take a PR?

**Comment by lspgn** [comment]
Thank you but I will have to decline the offer, this would make it more difficult to maintain future code and making sure it's still reliable over the new versions, porting in the case of an API change...
