### ISSUE TITLE
Transport Kafka - support mTLS

### ISSUE THREAD

**Issue by coredump17** [netsampler/goflow2#363]
**Is your feature request related to a problem? Please describe.**
our brokers use mTLS. I would like to use goflow2 with a client certificate that can be authenticated on the brokers

**Describe the solution you'd like**
Allow client certificate and key to be used in kafka TLS connection. file locations and key password should be able to be passed in as command line options

**Describe alternatives you've considered**
pmacct

**Comment by lspgn** [comment]
Hi @coredump17,
Thank you for the suggestion.
This should be doable and will try to address it in the coming days/weeks.

**Comment by lspgn** [comment]
Would you be able to try #367
