### ISSUE TITLE
Procedures to decode hsflowd along with sflow v5

### ISSUE THREAD

**Issue by Can-Yildirim** [netsampler/goflow2#43]
Hi!
Great resource @lspgn, thanks for taking goflow to the moon!..
tried and liked it very much, very high performance with minimum resource use...
Only problem i have right now is the hsflowd packets.
What should be the way to update the goflow2 to be able decode and insert new sflow types all in together to the same db in one machine.
e.g.; hsflowd + sflow v5 ---> goflow2 ---> kafka --> ch

```
flow_data | 0 | 2100 | extended_socket_ipv4 | sFlow Host Structures
flow_data | 0 | 2101 | extended_socket_ipv6 | sFlow Host Structures

                                        +

sample_data | 0 | 1 | flow_sample | sFlow Version 5
sample_data | 0 | 2 | counter_sample | sFlow Version 5
sample_data | 0 | 3 | flow_sample_expanded | sFlow Version 5
sample_data | 0 | 4 | counter_sample_expanded | sFlow Version 5
flow_data | 0 | 1 | sampled_header | sFlow Version 5
flow_data | 0 | 2 | sampled_ethernet | sFlow Version 5
flow_data | 0 | 3 | sampled_ipv4 | sFlow Version 5
flow_data | 0 | 4 | sampled_ipv6 | sFlow Version 5
flow_data | 0 | 1001 | extended_switch | sFlow Version 5
flow_data | 0 | 1002 | extended_router | sFlow Version 5
flow_data | 0 | 1003 | extended_gateway | sFlow Version 5
flow_data | 0 | 1004 | extended_user | sFlow Version 5
flow_data | 0 | 1005 | extended_url (deprecated) | sFlow Version 5
flow_data | 0 | 1006 | extended_mpls | sFlow Version 5
flow_data | 0 | 1007 | extended_nat | sFlow Version 5
flow_data | 0 | 1008 | extended_mpls_tunnel | sFlow Version 5
flow_data | 0 | 1009 | extended_mpls_vc | sFlow Version 5
flow_data | 0 | 1010 | extended_mpls_FTN | sFlow Version 5
flow_data | 0 | 1011 | extended_mpls_LDP_FEC | sFlow Version 5
flow_data | 0 | 1012 | extended_vlantunnel | sFlow Version 5
```

or another combination..

Sincerely,
     F.

**Comment by lspgn** [comment]
Hello @mrstellion,
Thank you for the kind feedback.

At the moment, it is not possible to fetch the others sFlow types. I am currently evaluating if this could be done with a configuration file.
You would need to edit the code of the decoder:
https://github.com/netsampler/goflow2/blob/17a96d991149c9bcc1481795de1c19b718163bb3/decoders/sflow/sflow.go#L132
And then to map it into protobuf.
https://github.com/netsampler/goflow2/blob/17a96d991149c9bcc1481795de1c19b718163bb3/producer/producer_sf.go#L248-L257

Let me know if this answers your question

**Comment by lspgn** [comment]
Started thinking on how to do it (branch `feature/custom-map-sflow`).
https://github.com/netsampler/goflow2/blob/cb238e17d1ba78cfea76e7c13d9f08a051541dec/decoders/sflow/sflow.go#L251-L253

I realize that custom decoding of certain structures (non fixed length) might be tricky with single offset+length configuration. Might be able to play around with reflect and how to explore structures (eg: map `extended_nat.address` into CustomBytes1).

**Comment by lspgn** [comment]
I believe this is resolved.
Feel free to re-open otherwise.
