### ISSUE TITLE
How build with transport rabbitmq?

### ISSUE THREAD

**Issue by vacilyok** [netsampler/goflow2#46]
I can't figure out how to put together a project with transport rabbitmq.Please, tell me how to do it?

**Comment by lspgn** [comment]
Hello,
RabbitMQ is not officially supported here, only Kafka. So you will need to either develop a library and fork GoFlow2 or search for an already implemented fork.
The former would mean copying [this](https://github.com/netsampler/goflow2/blob/main/transport/kafka/kafka.go) and importing it into GoFlow2's main file
```go
import _ "yourlibrary.example.com/goflow/rmq"
```
