### ISSUE TITLE
incorrect display ip address in clickhouse

### ISSUE THREAD

**Issue by vacilyok** [netsampler/goflow2#50]
i started the project Flows + Kafka + Clicklhouse + Grafana + Prometheus.  Run generate traffic with hsflowd service. In clickhouse incorrect display ip in field (SamplerAddress, SrcAddr, DstAddr).  
Display value  as 
 d�   �Rr   �U�^
![icorrect_ip](https://user-images.githubusercontent.com/88474007/139836109-b9eaf828-abd9-44bf-92db-8a3a01f7f792.png)

**Comment by lspgn** [comment]
Hello,
The IP address is stored as bytes, not as a string.
When you query you need to use the IP related functions:
`IPv4NumToString(SrcAddr)` for instance to convert into a string
There should be a few query examples in the Grafana dashboards provided in this repository.

**Comment by vacilyok** [comment]
When i query
select IPv4NumToString(SrcAddr) from dictionaries.flows_raw_view
I have error Illegal type FixedString(16) of argument of function IPv4NumToString, expected UInt32: While processing IPv4NumToString(SrcAddr)

**Comment by lspgn** [comment]
Hello,
From the Grafana dashboards in the [compose](https://github.com/netsampler/goflow2/blob/main/compose/kcg/grafana/dashboards/viz-ch.json#L245)
```
if(EType = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(SrcAddr), 13,4))), IPv6NumToString(SrcAddr))
```
