### ISSUE TITLE
Get template id in flowMessageSet

### ISSUE THREAD

**Issue by sharmarohit0013** [netsampler/goflow2#56]
is there any way to get template id and other packet related fields in flowMessageSet

**Comment by lspgn** [comment]
Hello,
> template id
Before it is converted to a protobuf message, you can access the template id with the NetFlow/IPFIX structure. This would need to be implemented into the function `ProcessMessageNetFlowConfig` in your own fork (I do not think the template ID needs to be surfaced inside the protobuf).

> other packet related fields
Could you be more specific?
What are you trying to achieve?

**Comment by sharmarohit0013** [comment]
Hi, 
> This would need to be implemented into the function ProcessMessageNetFlowConfig
are there any future plans for this.
> other packet related fields
this may include ExportTime

**Comment by lspgn** [comment]
Hello, unfortunately no there are no future plans for this.
ExportTime is used as part of TimeFlowStart

**Comment by sharmarohit0013** [comment]
okay, thank you
