### ISSUE TITLE
How do add  the interface name/desc provided by options templates into Netflow data flow.

### ISSUE THREAD

**Issue by ScXin** [netsampler/goflow2#57]
I have been looking through goflow2 project, and I know you add the sampling rate provided by options template. As we all know, the sampling rate is related with Observation Domain, so you maintain a map by version+obs Domain to sampling rate, I think that is absolutely right. However, I have a question **how I can correlate the interface name/desc provided by options template into Netflow data flow**. thx.

**Comment by lspgn** [comment]
Hello,
You would need to fork the code to extract the fields off the OptionTemplate (look at the SamplingRateSystem) and map them into the protobuf. Unfortunately this is not supported out of the box and is too specific to IPFIX (field index 82 and 83).
When using SQL databases, I would suggest mapping the interface ID outside the path (eg: with Clickhouse dictionaries, with SQL JOINs) of the flows to save space and avoid repeated information.

**Comment by ScXin** [comment]
Thanks for your answer very much. I want to create a map like the SamplingRateSystem to store the relationship between the INPUT_SNMP and IF_NAME/DESC so that I can match the if_snmp into interface name/desc, but what I can use to as the map key for this interface name/desc. Is the map[Version][snmp][interface_name/desc] right? I'm a little confused about the principle of options template.

**Comment by ScXin** [comment]
I have solved my problem under your tips, thank you very much.
