### ISSUE TITLE
flow logs are sent to /var/log/messages

### ISSUE THREAD

**Issue by vishnubraj** [netsampler/goflow2#64]
I installed to goflow2 using rpm, and using the below config to transport the netflow data to a file, but the netflow data are written to /var/log/messages also, how do we avoid writing the netflow data to /var/log/messages

```
/usr/bin/goflow2 -listen nfl://10.0.0.53:8888 -transport file -transport.file /var/log/goflow/goflow.log -format text
```

**Comment by lspgn** [comment]
Hello,
Which version are you using?

**Comment by vishnubraj** [comment]
its GoFlow2 v1.0.4 (2021-06-12T16:48:35+0000)

**Comment by lspgn** [comment]
Could you clarify if anything is written in `/var/log/goflow/goflow.log`?

**Comment by vishnubraj** [comment]
yes, the /var/log/goflow/goflow.log has the expected data, but my concern is the same data is written in /var/log/messages also.

**Comment by lspgn** [comment]
I am not sure the code is causing this.
Does it output anything in `stdout` if you run it into a CLI? Are you using a specific syslog configuration?
Could you run
```
sudo lsof | grep /var/log/goflow/goflow.log
```
in order to find what reads this file?

**Comment by vishnubraj** [comment]
Thanks, @lspgn  it was rsyslog that was reading the file and forwarding it to a different server, which was adding the logs to /var/log/messages also, I added the "& stop" line in the rsyslog config to fix this.
