### ISSUE TITLE
Go Reference: unrecognised license

### ISSUE THREAD

**Issue by ojdo** [netsampler/goflow2#70]
There seems to be some issue with go.dev detecting this repo's license file. According to [the docs](https://pkg.go.dev/license-policy), they employ https://pkg.go.dev/github.com/google/licensecheck.

This is how goflow2's docs look for me at the moment:

![go reference for goflow2: unrecognised license](https://user-images.githubusercontent.com/3525666/150551070-51bbc5d4-ab1e-4eb0-847d-9d0dcbd0c504.png)

**Comment by lspgn** [comment]
Hi @ojdo,
The license is BSD-3 but due to a mistake, I only added it after tagging v1.0.4.
Next release this will be fixed.
Thank you for raising the issue.

**Comment by lspgn** [comment]
This is fixed with new release.
