### ISSUE TITLE
Can not decode stand rfc 7011 template

### ISSUE THREAD

**Issue by bj1116** [netsampler/goflow2#76]

**Comment by bj1116** [comment]
Can not decode stand rfc 7011 template，
Device is H3C Switch，command ：
ip netstream template rfc7011
goflow 2 have not anything emit ，but not error.

**Comment by lspgn** [comment]
Hello,
Could you provide the command you ran, the version of the software, the model of the device and packet sample.
I will not be able to help without that information.

**Comment by bj1116** [comment]
![image](https://user-image
[h3c-rfc7011-template.zip](https://github.com/netsampler/goflow2/files/8359595/h3c-rfc7011-template.zip)
s.githubusercontent.com/15172224/160325300-57815e6d-3263-49e1-aa62-f45e0cd23502.png)

**Comment by bj1116** [comment]
> Hello,
> Could you provide the command you ran, the version of the software, the model of the device and packet sample.
> I will not be able to help without that information.

Hi, the pcap file have useful？
Thank you.

**Comment by lspgn** [comment]
Had a look, your device is sending NetFlow v9 ([RFC3954](https://datatracker.ietf.org/doc/html/rfc3954)) and not IPFIX ([RFC7011](https://datatracker.ietf.org/doc/html/rfc7011)).
The decoder was assuming a field could _not_ be of variable length (application name). Could you try the branch listed in #77 ?

**Comment by bj1116** [comment]
> Had a look, your device is sending NetFlow v9 ([RFC3954](https://datatracker.ietf.org/doc/html/rfc3954)) and not IPFIX ([RFC7011](https://datatracker.ietf.org/doc/html/rfc7011)).
> The decoder was assuming a field could _not_ be of variable length (application name). Could you try the branch listed in #77 ?

Thank you very much, I will test the or next week.
Then feedback.

**Comment by bj1116** [comment]
> Had a look, your device is sending NetFlow v9 ([RFC3954](https://datatracker.ietf.org/doc/html/rfc3954)) and not IPFIX ([RFC7011](https://datatracker.ietf.org/doc/html/rfc7011)). The decoder was assuming a field could _not_ be of variable length (application name). Could you try the branch listed in #77 ?

I succeeded in the test. It was wonderful ！
Thank you very much.
