### ISSUE TITLE
Add back "normal" output

### ISSUE THREAD

**Issue by SuperQ** [netsampler/goflow2#8]
It looks like when this was forked, https://github.com/cloudflare/goflow/pull/73 was dropped from the formatting controls.

The "normal" format is useful for simplified parsing with things like [mtail](https://github.com/google/mtail) which doesn't really handle json well.

It's also useful to be able to drop unused fields from the output by filtering which fields are included.

**Comment by lspgn** [comment]
Hi @SuperQ,
What is the issue with mtail? Is it the order of fields/comma of JSON?
Filtering the fields using a list should be doable.

**Comment by SuperQ** [comment]
mtail doesn't have an explicit json parsing mode. So you end up having to do a lot of extra work to parse the fields.

Maybe adding the "which fields to log" is a separate feature request.

**Comment by lspgn** [comment]
I'm doing some work in a [branch](https://github.com/netsampler/goflow2/tree/feature/formatting-improved).
This should allow field selection first.

**Comment by SuperQ** [comment]
Thanks.

I'm also willing to help with this work, I just prefer to file issues first. :)

Let me know if there's other issues I can work on. For example, goreleaser might be a good tool to ad to the build pipeline.

**Comment by lspgn** [comment]
Could you confirm that the following would work for mtail (or need `:`)

```
Type=SFLOW_5 TimeReceived=1623135901 SequenceNum=156625 SamplingRate=100 SamplerAddress=192.168.1.1 TimeFlowStart=1623135901 TimeFlowEnd=1623135901 Bytes=102 Packets=1 SrcAddr=9.9.9.9 DstAddr=192.168.1.1 Etype=2048 Proto=1 SrcPort=0 DstPort=0 InIf=2 OutIf=1073741823 SrcMac=ab:cd:ef:00:01:02 DstMac=ab:cd:ef:00:01:02 SrcVlan=0 DstVlan=0 VlanId=0 IngressVrfID=0 EgressVrfID=0 IPTos=32 ForwardingStatus=0 IPTTL=57 TCPFlags=0 IcmpType=0 IcmpCode=0 IPv6FlowLabel=0 FragmentId=46622 FragmentOffset=0 BiFlowDirection=0 SrcAS=0 DstAS=0 NextHop= NextHopAS=0 SrcNet=0 DstNet=0 EtypeName=IPv4 ProtoName=ICMP IcmpName=EchoReply

```

**Comment by lspgn** [comment]
For Goreleaser, maybe? I meant to add ARM builds but I would like to avoid dependencies (Makefile + GitHub Actions seem sufficient)

**Comment by SuperQ** [comment]
@lspgn Yes, that format should work just fine.

I was looking over the branch, one thing I noticed in `FormatMessageReflectCustom()` is that it's not using `%q` to escape quotes in strings for json format.

**Comment by lspgn** [comment]
@SuperQ could you have a look at #14?
