### ISSUE TITLE
Have TimeFlowStart / End in milliseconds

### ISSUE THREAD

**Issue by jotak** [netsampler/goflow2#80]
Hey @lspgn ,
We'd like to get the TimeFlowStart/End in ms (at least), currently it's in seconds and the ipfix fields handling better accuracy are all approximated to seconds, as we can see here: https://github.com/netsampler/goflow2/blob/main/producer/producer_nf.go#L353-L382
How could we do that without breaking compatibility? Provide a separate field for milliseconds, or having some config to choose time precision?

**Comment by lspgn** [comment]
Hello!
I [would go](https://github.com/netsampler/goflow2/issues/78#issuecomment-1112852109) with adding two new fields with `Ms` suffix.

Thank you

**Comment by lspgn** [comment]
PR was merged.

**Comment by jotak** [comment]
verified on my side, issue can be closed I guess

**Comment by lspgn** [comment]
Thank you!
