### ISSUE TITLE
Netflow v5 problem 

### ISSUE THREAD

**Issue by innogrey** [netsampler/goflow2#84]
IPFIX seems to work just fine, however when feeding goflow2 with netflow v5 data, I've got: "ERRO[0027] Error from: NetFlow (0) duration: 1.581644ms. NetFlow/IPFIX version error: 5". Tested on OpenBSD with native pflow exporter, however nfcapd digests v5 data without issues, so I believe that's not an OpenBSD implementation quirk. Did I miss some config options?

**Comment by lspgn** [comment]
You need to use the "legacy endpoint" (`-listen nfl://:2055`).
It's handled by a different routine than NetFlow v9/IPFIX (Templates-based).
