### ISSUE TITLE
Add the support of some MPLS fields for IPFIX (Junos MPLS-IP template)

### ISSUE THREAD

**Issue by door7302** [netsampler/goflow2#88]
Hello, 

I've recently patched the producer_nf.go file to produce some MPLS fields. Some fields were already present in the flow.proto file but I needed to add one more. 

I added this part of code in producer_nf.go (after line 335) : 

		//MPLS
		case netflow.IPFIX_FIELD_mplsTopLabelStackSection:
			var mplsLabel uint32
			DecodeUNumber(v, &mplsLabel)
			flowMessage.MPLS1Label = uint32(mplsLabel >> 4)
			flowMessage.HasMPLS = true
		case netflow.IPFIX_FIELD_mplsLabelStackSection2:
			var mplsLabel uint32
			DecodeUNumber(v, &mplsLabel)
			flowMessage.MPLS2Label = uint32(mplsLabel >> 4)
		case netflow.IPFIX_FIELD_mplsLabelStackSection3:
			var mplsLabel uint32
			DecodeUNumber(v, &mplsLabel)
			flowMessage.MPLS3Label = uint32(mplsLabel >> 4)
		case netflow.IPFIX_FIELD_mplsTopLabelIPv4Address:
			flowMessage.MPLSTopLabelIpv4Addr = v

And to support the new field "MPLSTopLabelIpv4Addr" I modified the flow.proto like that : 

  bytes MPLSTopLabelIpv4Addr = 63; // mplsTopLabelIPv4Address

Could you please take into account this enhancement in the main branch ? 

BR
David

**Comment by lspgn** [comment]
Hello,
Thank you for this suggestion.
Just catching up on this, would you be able to make a PR?

Could you create a `mplsLabelIP` field in protobuf and handle both
`MPLSTopLabelIpv4Addr`
and 
`MPLSTopLabelIpv6Addr`

Thank you

**Comment by door7302** [comment]
hello 

It's done. 

Thank you
David

**Comment by lspgn** [comment]
Merged in #99 and #95
