### ISSUE TITLE
Support for Netflow v5

### ISSUE THREAD

**Issue by acherla** [netsampler/goflow2#97]
Any plans to support Netflow v5 for goflow2?  We are receiving errors in the goflow2 adapter when attempting to deserialize netflow v5 traffic using the latest build of goflow2.

```
time="2022-07-20T12:17:31Z" level=error msg="Error from: NetFlow (1) duration: 2.79µs. NetFlow/IPFIX version error: 5"
```

**Comment by lspgn** [comment]
It's supported.
You have to open a socket for it `-listen nfl://... `

**Comment by acherla** [comment]
Per the config it already defaults to sflow://:6343,netflow://:2055 .  Which means the container should already be opening a socket to both, we are routing the traffic to 2055, but the above error still shows up.

	ListenAddresses = flag.String("listen", "sflow://:6343,netflow://:2055", "listen addresses")

**Comment by lspgn** [comment]
Yes I agree this could be improved by sharing the socket associated with NetFlow. This dedicates one socket for template-based messages.

**Comment by lspgn** [comment]
I assume this was answered. Closing.
